apiVersion: v1
kind: Secret
metadata:
    name: youtarr-secrets
    namespace: media
stringData:
    POSTGRES_HOST: ENC[AES256_GCM,data:oY895twRo7d98i8Q41vYCnT2dSzuIQwYhQ==,iv:jclTQP/fdu8qQa7Cl0UCqLFx/8dAbl0wEvm9Blby0es=,tag:lyd8gP28axl/Vc1KzwRzXQ==,type:str]
    POSTGRES_PASS: ENC[AES256_GCM,data:m1yhZyN7sC2qRAdoz2awRw06oxs=,iv:LFnvkpX9G1Q2pBaUQhy5cEXGqvXWwr+ifCAPIsHUwWk=,tag:9+IYrCKFXAZ0Wp7pNFyMPQ==,type:str]
    POSTGRES_USER: ENC[AES256_GCM,data:AWcWHU1UKw==,iv:zKwJ34HZSrZ5nH62Vt0M7l4v4aJTptIaAgsEDW16y0c=,tag:OfctSCyhZsVBxzZR6Zc+yw==,type:str]
sops:
    age:
        - recipient: age1tew57ke6dm4dg26ds595fjj4lmf52s4j20ewnm0d2yrkmekqaqtqjv2fjq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzcDJRbXQ0eU1vdUhCSjAy
            RVlZaVpFWjFGOXVFbnR5QkNjeGEvL3ZoUGxFCjhXc3lhNGdndWtVMmsyZWNNaGdS
            SEdXQ1hOS3hYdjVLSVBBUStLbWJINkUKLS0tIGMyVjRNOHBJd0t6VlZkK1pCV0h6
            dms2SklqVnNyR2dSK09iKzlNd0RPQTAK4al2jbx90L1iH59idy2dQLXyQDIM4XH3
            ivqmYGKtr0v1PQ+iThbBGVmEr4UNSKj35LaysZZNhgRy31Cph5DfLg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-30T19:05:48Z"
    mac: ENC[AES256_GCM,data:zka+JGDNWIfbZtHX76IN+TlxhZRdUljTxknQDuCcg+2SNzlay7/d2n1WMdNpj640tNR/aYo6jc3Y8MD+lcLpTbOVjUglgzmybrZrarIV/lQBkpCb2enheMg3odLc9Ro31sfQSjjcIdcLTZFx+UOjhAdqpGlD2ZBndVEfUzhZYAw=,iv:Stq/29liPLxPWZd6JaPs8yct+pr1+VPUV3NBIT5UHTY=,tag:U85LxhtnG9XtLoEQ/ER5Vw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
