apiVersion: v1
kind: Secret
metadata:
    name: youtarr-secrets
    namespace: media
stringData:
    POSTGRES_HOST: ENC[AES256_GCM,data:Fy37rV773nhIhr3u8HBYqFJwCriGH0jZ/A==,iv:TQ7s6Mz3QYsY9skfR3Nai/D4D+Msal3i4DYA3gPpE3M=,tag:ocZ+FRoeqjn0wIBcoDWdVA==,type:str]
    POSTGRES_PASS: ENC[AES256_GCM,data:VsNNDGwyuAljz5L+0yGMIcxJ70I=,iv:G+6R/xDG+LE00EphtJu7eXOFTqXw/PD1jHHD+U4D3PA=,tag:tXIJjcTcRWiqJrp9JxbLvw==,type:str]
    POSTGRES_USER: ENC[AES256_GCM,data:qM5tfVotoQ==,iv:pKGQtPVtZ9cpNJxO42L16gCE6cGEc5IH4/utx2FVYXM=,tag:MawBXI6LcBTGQlx6jFz0Kg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIMmhnQ3hsZkRRaytIb0dJ
            OGx0SWRaeWVhUDduTU9pcUN4eXh4VUNvdm5rClZSRk01VWFNVWQwVnVEa2lVOHkx
            MlhacHlaUnRyQkRjQU4wWGQvMzRFa0UKLS0tIHVYTFNaMUYvcURHWlcwTmthejYv
            V25pUis1WGpoTTdMZ3FlME82NXdNLzAKgqQXIxJgDI6gU15Pr6kd6n2Bcl1cTAts
            ErbywntIEpihpLzcLHohoYQHIpn+qgN9vG8vrqM2RZE1dIhg0G2BPQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1tew57ke6dm4dg26ds595fjj4lmf52s4j20ewnm0d2yrkmekqaqtqjv2fjq
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-23T13:30:57Z"
    mac: ENC[AES256_GCM,data:HgNQA1+RVchlE514g066jzzQ1H3mlpDHJGy0YEapLnnKUE9Ewk6fhjWUzuQ8xlU+6vjwGMDq2JwK918atMCqk/r19g+HznmB7OKr53ZrNaye85Fq2gfTp1nUQ5tfqZSZ3eYHgSTKhiF9Jybc/zh5z2AfXB2+HTF7WNr4g31a8y8=,iv:ll5qakNLV6AsWgdBSA+dTgPvQyUZPIttOE0BZnyG5Jw=,tag:qx1tROhi00TN0FWO2CIbEg==,type:str]
    version: 3.13.3
