apiVersion: v1
kind: Secret
metadata:
    name: youtarr-secrets
    namespace: media
stringData:
    POSTGRES_HOST: ENC[AES256_GCM,data:MkU5CY1Jw7SXq5KX2nIuEC++203Xqfe+oA==,iv:Kxtjb+PEGMJzRD+RnC2wZoWdj6rIer7/8mo6mj67dDI=,tag:WRyrguSKCgaC+YAi3JjnXQ==,type:str]
    POSTGRES_PASS: ENC[AES256_GCM,data:8r2ggG6J155iJ4JaKBy8iY5mQeA=,iv:zZ2zN/L70129JVepJ7QQgEHGNZeSso00s0Y4T1vpWjg=,tag:g8Nfu05vW18AVC4LceBeAg==,type:str]
    POSTGRES_USER: ENC[AES256_GCM,data:i0tK0dE2nw==,iv:z1M9uX6AqGXjJMRIPybG53kDkbg7S6ezRdFT+j5pvZ8=,tag:EoatiJJupZ0r/lG6XJmIZQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6MExBMkk2SGI1U05weGox
            NVNvM3dBV0hoZXIreFByRUM1L2RGM0RPRjJFCnA4MmZKL3JGbEV3NWh6Z2JENUNp
            NThxTVVtTlREYjRDdW5ZU2FrTVZOODgKLS0tIE85V2tzQW5IQkVrRURoMmk5cmE5
            VkFxY2N2Q2tTTVZ5L0JXOEZSWktwUE0KHRUmay3R835A/DlPn3jnQHIv3/O6f7yf
            rOz688TpfxjlTkyvYcmffjY+LrNU1zzLEWnRJocVsE6SA0hGJZU3cw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1tew57ke6dm4dg26ds595fjj4lmf52s4j20ewnm0d2yrkmekqaqtqjv2fjq
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-06T16:57:05Z"
    mac: ENC[AES256_GCM,data:gIigq3tSbRLEevtqIfRk/jdLDANbq/POo5qUC9cL8ZZ7LS/9r/T8Bi6SvoyCeElpk9ijKGQrrxB3slS3Je+lH2S9bVa3ua3RIrtCfg1kCaBt2E5+SP+dAAc7fZI7HLWnWV18OpFUee8Rg8LYb5wj/Zr2x+amlXMpwfujatU1zQs=,iv:il/sSmKfWAg8TUJEEyMFvjQ8W9LDn+Grn+1ttKT9H+U=,tag:KP3sH2KEHnzrJ0z8xYJy6A==,type:str]
    version: 3.13.3
