apiVersion: v1
kind: Secret
metadata:
    name: piped-secret
    namespace: media
stringData:
    DB_PASSWORD: ENC[AES256_GCM,data:Ubs3CQT4az6xiugQcy69lXDmngs=,iv:F+roBmelvcNpJvNwBjai1aMDuYf7c2ypvBonH9iYgc0=,tag:TNWXJQYqneYMv21TtWrjiA==,type:str]
    DB_USERNAME: ENC[AES256_GCM,data:1aLhohxk6Q==,iv:M0v3AIuyIGpayvax3l9AkJgoODmCtt4Oc4RyT9I1KUY=,tag:QsR4e0DSpXaANZA3ZQcaDg==,type:str]
    hostname: ENC[AES256_GCM,data:DFVnn4b2fMRQoe1ZGOV7Llr6Xkxx/PbNQA==,iv:1IrLLsIIQs3xV1JbKFQXvofSOvz++kJaS+rcCAk9ybM=,tag:HdhkZnsRR3TcH/m4jYpd1A==,type:str]
    password: ENC[AES256_GCM,data:m64P+bhSezTzNgRwh4b2tUa9Gyc=,iv:L0PGssIRW1PXw2/jVHyjSj6UqBGATmZegwTxfQY9Gvg=,tag:KaYpyD/xn/G9wph9pZEqAQ==,type:str]
    username: ENC[AES256_GCM,data:cpIdQfhP2w==,iv:q8TAE4yK3iQ7nk1dGQfD/te5MQ+SUSmb/oqiPEnnmZI=,tag:j+DAq956CgF1BEvqeiXcdQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0NUltRGozeGVGWnQ2U251
            Y05DS1dwTDhMOHdpd0FKSEpoZFRsMEdqM25rClcxTlZZNzVwaTQwZnQxd2hOcXZU
            NUhiQlJmTWNnUTNuMHdsTG5VdlRJWW8KLS0tIDNqS3hlWE9SWU5EZWFsVTRMUldl
            VkU4VlNhaTc5TW4ycDU3TE54NDZFcU0KEwtFJbgNtCqNZikxIRKQPz0FJCZ0Z01p
            MQJz6YFcXKdvhKm0lhIuyjAHm/KR01QqB6QNGJPpFpqbeRY95h5mmw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1tew57ke6dm4dg26ds595fjj4lmf52s4j20ewnm0d2yrkmekqaqtqjv2fjq
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-23T09:52:06Z"
    mac: ENC[AES256_GCM,data:enT69p6GLrzhKyJ2t9SzXgsHwD0DFP/pfkIknEqCdyek+ZMFSljyOhghVR/mnM9prRg/ZaCmaOuopnhjrSo6TOMWN3/35kpt/YsrOplTdmVYOmTV8hpkUh8Z2LQUMNZnCqjBRDRrnk60tqI/3ns7HNmAka6PUDA+4tQ6H+paXlw=,iv:5UZQIRkucQnNRUU+mtWtCx8r9NWIQfLaO5gKFMPhy1o=,tag:VQ+W7MPaA52YDyYqjMmd/A==,type:str]
    version: 3.13.3
