apiVersion: v1
kind: Secret
metadata:
    name: piped-secret
    namespace: media
stringData:
    DB_PASSWORD: ENC[AES256_GCM,data:K9vFoBmW7YHCt7C4eKKDAGwDGyY=,iv:9cv//HLrYlSeL+wKTKiM/3cMGDw7ccIC/5mgM6SdXBo=,tag:rgsK2inCyikDWM4Ln27ORA==,type:str]
    DB_USERNAME: ENC[AES256_GCM,data:8Crz8P8zZw==,iv:9juqFg4lCoxLqGMxnNG+vi1WjV8wFgbOErYNle9002w=,tag:IgeUpiZrGv6M/Bp59dyk7g==,type:str]
    hostname: ENC[AES256_GCM,data:81OVDuNvUyi7w/WIsMs9zBrDKo/pZZAFxw==,iv:utm9kmU5wn3dXA0f6P45yFIG+u1ZmLc+taOS0Lr8SNQ=,tag:oDdmwsuW+MfWRVikB0DzwA==,type:str]
    password: ENC[AES256_GCM,data:/fPVhCgrJe/KybdxDW+UEg+oSOM=,iv:7X0NDELi1jre6q41DurpMO0oFLgRi+ldy6Ip/6IQBuk=,tag:DNuza0VXEJ/gQUsGN/nvWA==,type:str]
    username: ENC[AES256_GCM,data:XNBgmN2UPA==,iv:yo0l23SXHh5NsnHjMXuUOaxoByCAnQwzp/A3CNpaduk=,tag:hBXwLORXZYIp08LZ5dKCEQ==,type:str]
sops:
    age:
        - recipient: age1tew57ke6dm4dg26ds595fjj4lmf52s4j20ewnm0d2yrkmekqaqtqjv2fjq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIdmJkeGxDbHZRYk1PdkZv
            aXk1VExpVzNYS3Fwd2htRnBwOG9xTW9Ta2lZCmloTlE0QVVkL0k3UW1VNVIxOUlS
            NmFvZzBDU3FTeHFFNCtHUjZ2SWlSK3cKLS0tIEx2YnA3OWY3Q3U4TzNoeHZyYitM
            U2s1SHRXYW5uMUlySk53UGRrZ3hVUUkKonH4KdoS9pxlvrhN+8eWeg07zs3xm2YX
            seYTQEyHBZXREvh80GYHeuwYYPfr2EbRxVbdFVRbw6v8iddQyvQACA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-30T20:52:29Z"
    mac: ENC[AES256_GCM,data:juEAwTCEvhBXnaOfo9yk1SOe/BMfje98O0s5mjP/iTyp7MqoVN84/IHOMldGWKxc3n5RWLqfn6FmcwJ+q9WpEsEErUV/c9JBZsD8bqxj6NWdf8Ivhhu5u0QsK2rMz1dkhx/95smqj5u6xB1abgZGykqiutELOWh/ONmacfDRb48=,iv:YWghV73HqDW6a4PIlEvS6sGxRDZ7SM/mDUjInX4eyJU=,tag:eUzsruzR51SY67NbrC6Qpg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
