apiVersion: v1
kind: Secret
metadata:
    name: piped-secret
    namespace: media
stringData:
    DB_PASSWORD: ENC[AES256_GCM,data:FDWpPgDoDPpg527rcRhf6x9P5SI=,iv:bxOIO6hB1fUnQbKSQrbiozEjU5OJqhXPhT/1m1+HeSc=,tag:OKLGKY4BbDUA9Vz1Hfudxg==,type:str]
    DB_USERNAME: ENC[AES256_GCM,data:Oty8jvwkVQ==,iv:8RA/Ozm52ulYIBdquXoZl6pBcRyKGMsqeJD6BY33P5I=,tag:TIWRkAzg1QRsWvht2+XniA==,type:str]
    hostname: ENC[AES256_GCM,data:K/Fwt0+y8pt0CuGSnxK2xxSirEAnnTPhYw==,iv:jmGoNui0WNwkxV+KW9EjPIBMHq+6DrIw9gq70YBelKQ=,tag:DQp8G2NZAucqzoKZgVtbLQ==,type:str]
    password: ENC[AES256_GCM,data:lFjZxeIzHbXknu/JfzLQnSK4OLc=,iv:m+QYaVUpWe8MdZNtzEfNaA2j99iLlfhImhgbDWFsjgA=,tag:zPhLmF71Pfj6QbmPh23fTA==,type:str]
    username: ENC[AES256_GCM,data:b20QFU9D7A==,iv:FbCJZbYh0/4nPO/pio4AnQBZb6k0dQ+Efp6GawbluKA=,tag:7VVH6WzpkCuw3U8CVaoRIw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkVHk0ajlQcFNxdW40WnIy
            TXFTUk51eEdGRnMyRHB0MlVlcmwzVTcwZmlnCkRpcHdEU04yREhvd3JVU1hTWHZ0
            TVNkN0MybE9YWGVSNEFpWFdXWEZ1WVkKLS0tIHJodGFGV3Uxc0xYbFphMnFSMWFp
            MWExUThRR1MrR0Zhcys2SmljQTF3TlkKwE9YD19hB7YkBTN1B5YjaCi/X1/fB3oh
            LLWEBowD89TNnsIBc3snoX4hIxWHgedI5oyCBNI6+cX5yOK3mQQT2Q==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1tew57ke6dm4dg26ds595fjj4lmf52s4j20ewnm0d2yrkmekqaqtqjv2fjq
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-23T08:41:04Z"
    mac: ENC[AES256_GCM,data:B9Y+HMACPkCcd6U07zH4eW03+zwD5bQvto0P3YBJeGgvlCUo9bsWzY32NYzmYe7WOlBzdmxQn+Tq5q0qf50ryDzwnrQVi1LPFFoZxOKipdWVwCCoo/M2cvUmQu9+/WAWzfx2iP0P4e6kz8wN+PPtREC0y7ybwWivTaUVl7KB9Jc=,iv:+Fl34+y193DM4UMEiIl46U21I9PFx4IXPUS103ocYw4=,tag:nOMyQtNlowi527OI76WQOg==,type:str]
    version: 3.13.3
