apiVersion: v1
kind: Secret
metadata:
    name: seerr-secret
    namespace: media
stringData:
    SECRETEncryptionKey: ENC[AES256_GCM,data:CQfBpQHdPpddPmd7HJwh9bl5LRubRqKj,iv:HQhtjIwbiOQKChTrLCBTueRwRIPbt6n+g6YIrGRK+yg=,tag:YY43ACOUsCvps+gqeLLzIg==,type:str]
    SEERR__PASSWORD: ENC[AES256_GCM,data:M4+pFqfRpujehAQfJD6EpA==,iv:/KBcle3RXnVs2SaKo31U/X6PTG/uDXTFR7BZzdWYxpI=,tag:i0JYS4UM7RaMD2q2Dnd+Vw==,type:str]
type: Opaque
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGVTR0cEFTd3BhcXVQa3Za
            aGNsTmpVVytCUkloTXJUYWgzOUYrZG5kZnljCnVQUElKejh3K0RkN3ZsV0FCQyt4
            VmRkSHlta2hvMklmbmFLWmV6dWVXT2MKLS0tIFFoUDRZdE1ncVRGMTEyR2o4ZEhx
            TXFiRjlNM2tmN1BIMnhZRGphRlhQaVUKWCckoXNi3Vg6lfJo6eiiSc0f+i7Nhr1h
            xSn2JvuZBam35lzzZ7CKMDn2oE+rEFulfSy+3Q+5x5R5pYmHOQKJ8Q==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1tew57ke6dm4dg26ds595fjj4lmf52s4j20ewnm0d2yrkmekqaqtqjv2fjq
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-23T02:19:29Z"
    mac: ENC[AES256_GCM,data:eE093jRtZvFEN2R95C1M1twHJWX2u87RwYgHjh83hIOuIBWgN5i1NSkjo5neKgkyQ61dnny2pfjnJc9UqGi3lyNeil3n+5qku2TSxrE/vpa9Ub0Xj0rmHpXsmmjbY5BVfUbjs2f0PKxeY5YCowmogPM+9cPoTumjiShW4qiHYVs=,iv:9XhbjJq5xPWD+u6sJ9nBp3uta/9CCexKV5NE6LH9/KQ=,tag:MqvIL1hi4elz7Ctixx38wg==,type:str]
    version: 3.13.3
