apiVersion: v1
kind: Secret
metadata:
    name: seerr-secret
    namespace: media
stringData:
    SECRETEncryptionKey: ENC[AES256_GCM,data:WxAj5bMgm2rxD4uy4PxoaK8wJ1T/rEf0,iv:asY7DM/UjP6CnT31JoHfkBrRjy0agwnjQw2IFJYzFq8=,tag:n8yR9pnCgQQlAx3kLD1WOw==,type:str]
    SEERR__PASSWORD: ENC[AES256_GCM,data:6NOwpku84xThAL8eTv+qmA==,iv:kWkoFPcRZx/5BP9LFA/U+suOGZDjI4PHVH0l7XzG4cQ=,tag:HDo5g7al56bFWn0ccmKZeA==,type:str]
type: Opaque
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzQ0pZY2dEV3ZxQmpwR1Vy
            Q1MxdTBWMjZBUGxrVlpLS3FSQ0s2MWZycFI4CkUwSUMwd2Vpem55ZzJGRHNGWmxU
            L1VRZlBNSjFJa1hJNFNhK1g4c1F6ZmcKLS0tIE1IVUtZSGZwL3JpdzF4clJNVEht
            WnBjZWdNdHE3NzBNcjduY0tQa2JBT2sK595ei2SFkED05dD5t7RrXgVE5FSqngRT
            PErRV0+LL8h+QhviYVDxYOU6hXDEIhPbJB2Q7CBIWQecMf611BGfAQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1tew57ke6dm4dg26ds595fjj4lmf52s4j20ewnm0d2yrkmekqaqtqjv2fjq
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-23T09:52:06Z"
    mac: ENC[AES256_GCM,data:3e2ua0eHcOaTPxkh2xChs5tneqw4db5DsQCJ5Nnug2ota2FFrRaYyTDO3FqfPseUO6BBgBlaFwj3fwVcB2XkndcxbER8a+NV/87HV7N4B2eumR47NimCONxfpMybSCpFbb5uMqXPv7LvaZwfX1v2D1CoEsZsNINRrNtXNPvKh/s=,iv:gWTPyN1caEkw4A1JQgmTQkxJ9Eygs4KCCytPVpf4+FU=,tag:+X+md+/9DRC7LIWbTAbu2Q==,type:str]
    version: 3.13.3
