apiVersion: v1
kind: Secret
metadata:
    name: seerr-secret
    namespace: media
stringData:
    SECRETEncryptionKey: ENC[AES256_GCM,data:vbKefG+/8MOYSe1TtBYRxpv8LAurwtqm,iv:MbWdvtaLHx5cOYUh+KFM2Znq83JAHydmdVmL+hD4n/U=,tag:oGEo7JOmMfZJew6rpcFH5A==,type:str]
    SEERR__PASSWORD: ENC[AES256_GCM,data:XOc0G5cfiJ5AujahXNrWRA==,iv:AzAk9tkjJaBcPlMRvxDqZSG4Ch3toQW8bo4jQIMCZPU=,tag:chMuLA/AqF90p+46rKJSWg==,type:str]
type: Opaque
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4WC9ZNHZjWlY1VittZ2l2
            djV3ZTYrR2ZVU3ZOVWY2ejlDVlZoc1Nwa3dRCmNGelVJa1FFYlpLODkxbGZyVjlO
            alpSLzV1RS9oRzBHVnZidU1CdFl3c3cKLS0tIGxTZVVGMHlBVnl3d3NDNlIxNXpE
            L1M2SldzcHBKRE9hdGw0V0svRXlLUjAKRfh4kIKr6S3Fo3L6EysGOwZBBocZ7sv7
            MdtJpW8TKzQz2PtEne5AUCY2MSXwGppgf2zK2x3/uebwTguSQmQcfg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1tew57ke6dm4dg26ds595fjj4lmf52s4j20ewnm0d2yrkmekqaqtqjv2fjq
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-23T13:30:57Z"
    mac: ENC[AES256_GCM,data:wzbTxsjNm1GNYwCvKIpIAWu2ew4Fb7R6cNXHlNqYZUvwq/KG72bqUmCqjjxZeV4PHZDyOeby18ZStwf1YTcM81FYEP8eWmrdpARQiO6mpWD/Q5jl500HIBcb6uO4c3l+liUkvwOHSfBWkjq72CWPnS3O110rvRU9FVaLxSTz91o=,iv:hrZHfI2DXfcGbqI6wRXizcC2gdWFgauGorVMSdkvBvc=,tag:Y5PmjJMUVj2zoBwfbdzgqw==,type:str]
    version: 3.13.3
