apiVersion: v1
kind: Secret
metadata:
    name: lidarr-secret
stringData:
    arlToken: ENC[AES256_GCM,data:b/IgnLodq5D+W0CXMtHRi9lrCsY1PuZ6lthWQJRbKnC7flvx/LrEjuWpKNV7fyUDqWTAyKvOSy6Pt9745p0WmuX702geNGUcQ3EmaD3jJpcUuog2AVlkNtT8kyuGlB85S5JEf3FM6DBYNOV6ai2qeB/4MtKgxL7/PKU9E26MRBvdH2yG+7Kr6YtFQR7ASf2e8ON2VNTI7pMvCpl7fWU/Ki4QW02QLl1vG0XRATB6IVgNtQyV0MhbCiSuUrOuW7X6,iv:/G9dpmfNCLT5CFHVljwclgJaL1Mell9LTFsGMW6CDLc=,tag:3ezTXPQqR30ZbkHUOl/A9w==,type:str]
    plexToken: ENC[AES256_GCM,data:+4tV4FIS/D/z5k4/KCzc8u2ik+k=,iv:XSJHA88I6j0ey8s794E9Id5pK8AUgCtGaUEhYFy43Gg=,tag:Tuc0d9RDiC3jVBD4182IPA==,type:str]
    plexUrl: ENC[AES256_GCM,data:GJG43Gy94Yqu5qrs,iv:tKDERUua+eHwRkzs799Eff8sedqESnWwhPrZWuqvDJs=,tag:1dBWWGY7YBgBgAR2xM++hQ==,type:str]
sops:
    age:
        - recipient: age1tew57ke6dm4dg26ds595fjj4lmf52s4j20ewnm0d2yrkmekqaqtqjv2fjq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6SzRJZzQrR1BOT2NSYTdN
            WHo4L2pldWhWN2V3WGd2OVJMVTZnSWJhaFg0Cit1TWJBNmQ2NGY1TmNxZzVtdWdr
            RUhvNzRzL0pNV1FZNFN6SFNvUzRqWjgKLS0tIEM4Rk10WHN6ei9JRlhSWDNJeWNL
            emVPQVEybFh3eTJ5eHhzTUFZQkQrR1EKCJMFfkL2DviAug57cC5vLpyBd+Owbmqx
            Oo0QQ937KbTuc55tkChj7Hd92KPsC/3W7OwosI1m6H4ockUhM941hQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-30T20:52:30Z"
    mac: ENC[AES256_GCM,data:rmkBTNiU/f7ZRUjcDrB+2JUJ5kngGuoChW59+7E/CteB3a979BiX5taCYfYGkjNNGxbtwN/y9SyCuPh1/u/reP713QIbK1maXJnzYQ/5RSo7fOpfFsD8ZgJYoXhG0yrenYnWOVqAYaI3VMlMeOR0rqV1zx+XnU2yEqPDI7CsAUs=,iv:U2017z10XjyXIMOC4OyyQKIGn4Ju2nArKAZpB6XVDZw=,tag:vuMn3CsT8lX1d4UL4Xojdw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
