apiVersion: v1
kind: Secret
metadata:
    name: lidarr-secret
stringData:
    arlToken: ENC[AES256_GCM,data:w9kM1y/CnLV4JkRMoc9LmMqNFiOge0d1q7dlwNEfSOJBKw2NKlzuylK/Fx1p/R3wEnHKtreHOJCUciLWZIBHxOHZVkn5KshSRMZ2FYG6cyQMseS90p3TDvx6fItw0CwqG1ep0kMegJcwCMWIRWkffUTYmatPB3NGvir4O+Pn6vpFidvPFMWWmWMSmEFmxmv1jNL8DatH6n6PNua/6aq+rk0KAEMevHbLEk58IbO0ytYpNRFJzAuAqhDXd6m8D+LJ,iv:/nqKV5eJe5L2DEt0cnnj9xPbo0vK5MueaLf4zsgJMiw=,tag:j7Bp1ccTZsmvj7i3owwTyA==,type:str]
    plexToken: ENC[AES256_GCM,data:NUnXKz4YqAOsbIzYshRUfZYFnik=,iv:7t9GgLaFk2UoW7lRk28fYut5dfSUqcoBhtUilPk5LJE=,tag:2woql6tU6CaKEDOM0mCrWA==,type:str]
    plexUrl: ENC[AES256_GCM,data:F6IbF+vuNbHgstpC,iv:5ee+E4Iol8E6APFkZFmVxmKFtSYrSi+xor6OHu5+gJc=,tag:X5nrhY2dAr2HsEQqK2Gxkg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwUlhZaEdUa0NGZG5ZbkRM
            VDVjN0xaT0ZaUHBoZlZJZFlyUXcxby91OW5rCjlpZEV1SWx1RXNKTG9CQVJPRDNy
            UjFmbEt6S25YMk1XSi9OWjVER0JLc2sKLS0tIEpwVzlBQ1BEdnI2aGZCY2puOE9R
            bDhQeDNGT1g4WHg2djhBcENlZ3RROFUKlM9aXGcnoxw/QAg/DPE7Y4kgGcgd2hR1
            Yj1kZhw/dhkV8S3Ces6H8/uzr9b/ph0Xz0Um5ZRNWodQKw59qVuCgg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1tew57ke6dm4dg26ds595fjj4lmf52s4j20ewnm0d2yrkmekqaqtqjv2fjq
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-07T14:54:00Z"
    mac: ENC[AES256_GCM,data:Rew97lm/HOi3JQsKWQRIzNVRdOkUf28M6DEszGRr7/qT9OMZoKzTw/SHtO9d9OVb67WvzHxlNHgXYA5/WFBDAQmin8wx3qHT3QPeBlwkolxwXSa5/QkaBRqs7se+3zV+BnKWGAAf/o8hXNMUyZ1jngH3F/6P09jC56N0zPIJzy8=,iv:V99h7h2g4M14pmKH/pe4CqCjdnYJRxcFmyRZA7xIj3c=,tag:koSl8SJTkxEiAlI2c1QBUw==,type:str]
    version: 3.13.3
