apiVersion: v1
kind: Secret
metadata:
    name: lidarr-secret
stringData:
    arlToken: ENC[AES256_GCM,data:SM8nZT39t0whAz1kDBsvy2hW7+FSOmi6Jpe6Jj7CvzjAm8HLqzMRmEr2GAhFbLJdCCNvf75zuEcsjPHQzTWR/1FhyZhRfhl8p56kxuVINsdelgC4N/Rk95gVfRScq0Mc2rmiSp+9JJCywQLHUwDQHetEHiPJXFIZg/HCK4Zk6TRRfIGg/2RoAvYsG4x0uGl6VK5i4YZCPAhPJFlRY2YjGabOTrF9TAfYZaAAhvUmhg3wZG5+iAmttJjxBEDJonGP,iv:iPSU5dRNUqc9UfkAKBevaEaPptmIMfGFokpNQUBTT3s=,tag:1OaPDJs+2CIiygVISAfzxg==,type:str]
    plexToken: ENC[AES256_GCM,data:bJazJIG8Fnxxx/Zo+iWxSg6LfbQ=,iv:vfdQvzb3RSuY+XhT6r0ASq9thB6BVEw0G6MpeXgbXOA=,tag:g+LpMeP6PKhE0enJKyRTQg==,type:str]
    plexUrl: ENC[AES256_GCM,data:/jb2V9oH6PMcTeqE,iv:U5idw5BXXuAEzZmaeAPIaSMxzEhe7WMkQk2mD9NLYgs=,tag:oRVxjcXF+fFT5H7rxgQoNA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6K2ZYcDdteElWZ0tkVk9D
            ekc5bmErQXViR0d2dTEzWEo3RkE0TkYzczBBClpwMDVTMDBjalMrakFxMHZBZVJO
            RW1SNnRKdnZVV3ZxUk9tY1B1RG5JOWsKLS0tIGtyYitZMW9XVG9Cd3RKRjBmZFI5
            Z1RCb0gwaHNqQUFZdjQwckw1NVoySjQKoS1Ax+C7prHc09mAqZQ4/SnhZkvYw5zO
            tnDadp6pk3IhsH14za4r538Rek3NbGh8PsVZyiSYoOtv4OKfaGS2rg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1tew57ke6dm4dg26ds595fjj4lmf52s4j20ewnm0d2yrkmekqaqtqjv2fjq
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-23T13:57:52Z"
    mac: ENC[AES256_GCM,data:Rk3oYlluJQOqdnxRlXrjNHt0uz4PRvm0Huosw8UJe1S07slJXHHo3KtFL6oo+XVdPRC/pCnUjZoozgv4c9qauqPuN3RaeBWv/WUDKiev1BUp0prHIQQFa7Y7pW1ZT5ma90ZnqK0PTE+uG4q6ryjKctdAyrEJYje2glEF0biiIok=,iv:aoxSKRiG4vrxNCdSk+6q7RjNYLoskU3uoz2D0F07U30=,tag:4UlNBM0M90Currnd0Jzt2Q==,type:str]
    version: 3.13.3
