apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secret
stringData:
    TUNNEL_ID: ENC[AES256_GCM,data:aNqqF3hX03B8myWvmVY5UNtSOwYxlFhwZU7Lma1EiQ45XipK,iv:NdxC0AE1e9gg33Vgb3rFVq3AEgemet64roZIzxKL/Lc=,tag:29RaRfzKMhnUJadIL7ZtNA==,type:str]
    credentials.json: ENC[AES256_GCM,data:FJUHM2RjZ1YzMIhTMDWtMGnUODj3Cg0QXyF6EzJnELFiPEml35tm+nyo4vcmLI+4AMlmdbvpEE4C3zyxLJqMi27uvstLNVX+cRodOyFbdIhg7iLuBiAhofVNzr7CqFMTUpXF60ImiMBV5+ADxM6r+wuNg35MDCcWdCNSuZ52y4jMuwcLVBqYayV6xZZ5FwBMp0oXSgJQBcImBmwcaLBf+z0HiQjKHianpwItVqZlkw==,iv:5yht9xP6S82u6LAzReVdIFShzwsYmKb9cTxpjLLdVFk=,tag:7Fm4fqbmBKgfWO49cQWpVA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPZ1dkMUFUVDRuRVNUT1E4
            anI1SjgxMmVCNkdPbksrREZEOUlWdUFUQ3pzCldNUWY1OUdPbHRyeWZUR1M5YU9R
            L1hrUXFBTGc2NTk3UCt5OG1KVUlPclkKLS0tIFBmRm9kVGlqczk5djVEY0JYR2Zo
            MWM5VlZHWFl1ZEUvQ1cwM2tvRDF2ZVkK2yBQ9wTIytJinRwoNFpE8pBdUH1ckUfj
            DpFlOPwbbms3zztLlXnrpXEycGod7AcynedY4DC4vv/vwyw3Jsad1g==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1tew57ke6dm4dg26ds595fjj4lmf52s4j20ewnm0d2yrkmekqaqtqjv2fjq
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-23T09:15:46Z"
    mac: ENC[AES256_GCM,data:HBOkfcV+lfllDx6xBluaV+VgxSneo1QyE6Jg3EwR4YlpZiw4uAaiK/hujMkDgpuEts0L806QGTtabzdq+QPtatJ2323jAFnSVlgZhTus8s8he4sfOMnwe/Uqp3FA7SkjC16sXNhBaukLAQXBlhpxLwolLkD1FeNYY5Q8Re8A/TA=,iv:r2RbjKnLYGbj1V0MSpSUqqiiJuzXgld2LkI+VzVk66I=,tag:DKTUN3OHul7cszvwBo8A4g==,type:str]
    version: 3.13.3
