apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secret
stringData:
    TUNNEL_ID: ENC[AES256_GCM,data:Sh+D9rpQsIbgPPLCOph84uDRAaQLlm3DGLwZ9Adv60lgNTaR,iv:fX95qlsU7MloP3DVjYBVp+1V6DtDQzSjOFe7akUKQiU=,tag:oyJyAall94Q3Y7iqt3dymw==,type:str]
    credentials.json: ENC[AES256_GCM,data:O3zz2xlc61MW0wMpqQxusbt+DGS+ZFpstw9Cj97b8Wgaz3E2yPAabWUWA+KFLA9sIK/C/MU/0VdOTqpCnTWvjtjYZee6rN/UCyOGkragPq+42aexFt7RiJ407DGpGlSu6qPLghfQ7/v5bgqG53eXGVHQtdz8BcPlE4h6vaJ0kapzK22AD1n/EYh1dyR7lGXZlQLwbNvKSdQeNSoq/B0oofMht5wAGXLh/+7ngKLPMA==,iv:Uli5pUjluB6hgRovAVKqCWc2wmuA4iNEQu7M4L5K3ZQ=,tag:lJ0LrUJUjlRRyQxJnIlSsQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYK1NQR2p1LzFiZmtkaWht
            ZWt5MjJ6QVNrbEdkZkJHcGcvYUw3YmJybEFJCkZZQTZJeDFycHQzRUZmVU12NEdH
            Mk9sRmI1ZGFVMnl6MmRjd053ak1INmsKLS0tIHhWTWNjbUlUL29DRnZ5aThiNG1j
            TTYxMjE4WFh3bjZ0bGprQVhvcjEvZkUK6xa73lFsxC3hnHzReN4lf3JuRF6QjK9I
            n9yD5+KIxYF6r3FgZ96hsnIR1uUpDc7WQUuLphSyGKsM/+lUbNhFlQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1tew57ke6dm4dg26ds595fjj4lmf52s4j20ewnm0d2yrkmekqaqtqjv2fjq
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-07T14:54:01Z"
    mac: ENC[AES256_GCM,data:/z2hJM4P01ia3RruxmF/YtjC9Loe5QvDcgYSpJMosBVf69OyFEqdUvLz8eBQSeNNRhg1soGH4y2mSE9TcaogiC7I84db1p/kluKlKw3Tbxze/hTxgTdwUn7+oVZsT30Fm2/CpeSQ6GkwxDkI8Q/+qqluVHUfpUJWYjaNW/elWIk=,iv:Jfj8B8Sj9h+xT1GEOlTmSB1yTUY2xnOzhB4AqggyyF0=,tag:+wNAUTcwFCDtdkaxR2aVmA==,type:str]
    version: 3.13.3
