apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secret
stringData:
    TUNNEL_ID: ENC[AES256_GCM,data:TNQCpaYH/8aC9uLG+RR9PvioFbdP7XAD3gbxjO0EHakT4hxV,iv:to9Ufgmv8qkMRuXhwTDegdXLLL8W0wMc04FUx3N6cqQ=,tag:bcY+MhIGVhmwW13Z1/y/uA==,type:str]
    credentials.json: ENC[AES256_GCM,data:SlVyAV0vC+fsuDprTS6n/V31TME+R4LUs191+VZxmqerhnQvu5gur2O0mDJrQ0ajLm5CHe0PowMpzCZ2hpunC+Qsd4QHg4Vubs3EALaNiKRWt2GMjG+Uaga+cOj0ZipOft+HFy0dELo7/HWOOClrOeZPs4tx4dHhVi5R6eEZkWb26YvxwVarFngbXTDapk8ESnq1dY2mBT9Txbj2x+8ThpFC/tQAp8JnITk/HX4ZrQ==,iv:HIJoakPuBPgGLb9XYJYhaX2vTWPdHFz09veKs5LaNpw=,tag:j5M3E+IUeYRzQwBE12l3kQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaOStGQW9sT3F1a21wMnpK
            S2hRckxzK0c1OHRvM04zS25HNVBacTV5a2pzCktsVWNWWWNqak1uWWRPZVMxT2ZR
            VmtMQ2pZS2I5MnpyYWpPUHljOW1Oa1EKLS0tIFlGVlVzU2dUdExJNnozTXhjV0dI
            eXZEcVBOSnh6SHdoc25nZEJYZGFRejQKq/UC+hxaseb75IQuCqhq1+LNbMOsqTm2
            Kjufm1eERDk4sbRN2Jy7vCvqZOi0xW2TTTpLo1ZmZzUGWSX4ICJFRQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1tew57ke6dm4dg26ds595fjj4lmf52s4j20ewnm0d2yrkmekqaqtqjv2fjq
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-11T00:18:02Z"
    mac: ENC[AES256_GCM,data:uhkX2kC9T170IsgxOSfMZTOAHSNoQi2mEyVMKhMrL8DL0xSQEVyAhyEQS6wz/575wmQQY53bLalMEOxa6KAldchmxKIq2BsxECYth2kD1uLGoJlhAcNx2IloJ3+pEGxB+cYD8iUUBbYOM51O8yxOmjIqKl+MqVgw2GE/Q+ujjAI=,iv:8XwSPFjFGw6WDMuk+++8Q4742Yiw4jogZ6mRJcPnxS0=,tag:GLrY+AEunFXKQBKfWV7tNQ==,type:str]
    version: 3.13.3
