apiVersion: v1
kind: Secret
metadata:
    name: wg-metrics-secret
    namespace: wg-easy
stringData:
    token: ENC[AES256_GCM,data:DRd4A6SRObGqcGIvYdyt1MBzSYyi0CoQIkuf3i9B21U=,iv:0+c4kNXr01cqIASXLFNQXZUcE7Y/sjq+so4iCRyo/RY=,tag:1eLIL+toaAtzaQHoNTBl2A==,type:str]
type: Opaque
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwTXdwK3o0VStZczhrenBr
            UjBlT01pM2lJZDBCZGpIRlh1NzcrVlJJZ1d3CmY5UHFQV2FnU1pGMmIyWlNLejFY
            UVJwOG9VV1pTQnNmOWJyN1FCRnZkTVUKLS0tIGsvc1lSai9pbG1ZMVhyNHNZbGtn
            RWVuMTBIUndqVFlkSEQ2czNtYU15dkEKuPjqL6ALgrbYtbMbjdcq37p9NTbVVep3
            xLvSiz14ZbcdV+gM0/DYswA9Bof5CkW1oBvX9dDZlLX7FN3nm7H1sw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1tew57ke6dm4dg26ds595fjj4lmf52s4j20ewnm0d2yrkmekqaqtqjv2fjq
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-14T16:22:40Z"
    mac: ENC[AES256_GCM,data:q4JXbixdY3IyOacn91+7T+WAA90+6qLYnIMsfFuxaFsV5jytwboHPgo5zyXydKcdvgLnB12fWb4y2w6bj3G6FTYOE7G+ku73XA2Q41oLnsjTcPOlyG+gFqzuzFbhmkfBDo5V9XJA5dmVYYq54Cg9Ak52flt+tK1VbwxenNBYyhM=,iv:UP+1KT+PIt8Lii6GbiD8rXre2KwHkdDo+AvK6iRrd+Q=,tag:W1i3uF+Q/k7Yx6y4guKb3w==,type:str]
    version: 3.13.3
