apiVersion: v1
kind: Secret
metadata:
    name: wg-metrics-secret
    namespace: wg-easy
stringData:
    token: ENC[AES256_GCM,data:81lR+6gHkEgCKjXwfjPW2ZCDMQgeYX8SZtPQhLIq5kI=,iv:PtWef0AiDNPSIrbGF+2p8aJ4GjDDPhvINmA3gtzTowg=,tag:ieYvq80nFJLc/KWeqFrcHQ==,type:str]
type: Opaque
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoenFWMkJ0SWl2RVhEZjBK
            Q0hZVElnMXJOanA3ZzBBakJGWnlqTnRDZGpVClZQNmJVRnlGdm9pME9yR1FSTUFP
            QUQ4Tnl3Zkl4MWFGanFCMjhHMDkzTDAKLS0tIENzVDVEWDhSaG5vQWwxc1dVc2VE
            VHk3RmU0U255bVdrY0NEMnZQR2ZDa2sKkkImFfb8t45DUuBYr6eNte5x9xfc4sKy
            V/fV7ySlV8hjM13IHq3IilMalX/qkVF+2r4y4gkmOXOteEifxWwE4Q==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1tew57ke6dm4dg26ds595fjj4lmf52s4j20ewnm0d2yrkmekqaqtqjv2fjq
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-23T11:03:14Z"
    mac: ENC[AES256_GCM,data:IS36VbrGVX5teUP7KIbN/p4ofda4ed5xqNCTPPaw9KbwpbGUWS94FI8sk0jS+LJkDBw0Gt948GTclmVuycoVVjDPc2EbIBtoPTNPSOZQux/h/OdiDULuTPTbVQhAc5PSoyJOLboD9xYLcvsyBh8nckwEEf/2j/E0WSrvHKdMi+s=,iv:Qgc76cdM7GNxbfhSkMiLBV2w2m60oqrf+S2xSZy6ar8=,tag:ViiTkQDWtnra+794GZu37w==,type:str]
    version: 3.13.3
