apiVersion: v1
kind: Secret
metadata:
    name: wg-metrics-secret
    namespace: wg-easy
stringData:
    token: ENC[AES256_GCM,data:jV2NChgcTtFzHv62i36iDLQEOvRMNmL7Juu73IXEzeA=,iv:N0olgcNTUURjYapck2c9AaTItXGfHQ6a3hUh9JFSAm4=,tag:33rBaXrMG7FPXKoZnr+6zQ==,type:str]
type: Opaque
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2Tjg5a3lGZC9yUXpzZERz
            dk9lTHpSNlI1TDVpQTZTb2Rha2d3VVgwckMwCnhFYTY0bndmQ0xLU3JhdXovbnBE
            YS82KzJmampZVzFWUzZnUTFTSU96SlkKLS0tIFhJZnRSQ3pSMEdqdlNIRUNHZWds
            VnFDaTA3VEw3V1dKMzQ5QTA1eFhrTkEKl7Ua191+KkgUC/0S/brzpL8wNbQ0XWWa
            m8jMRt0vXR9+O4T4tnCmztbABHIhwploAVcWlCgGZsSMh1CcjzypNQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1tew57ke6dm4dg26ds595fjj4lmf52s4j20ewnm0d2yrkmekqaqtqjv2fjq
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-22T23:24:24Z"
    mac: ENC[AES256_GCM,data:2SM9rd3/+UW+U7W4ZMhSQIjOwvmnhR2480RTUhZgRz485URgYDU4rI7TRS2KM8FGWkzFo9F0RxiU0YdwJFeQrKNNBz3Xdrckmz8h4eued8G0syMCRXG6GSrXHPhVhoKbpIRU/5DB1d9jiFgAS4GDn9DTehUypL+vaQ7veO92UPQ=,iv:lxXvp0S7BoyKR+7vHvLwxzw/C3pHlF9XqpxSMMyfE1M=,tag:IegS07A9X0wZ6ezvzvT1Fg==,type:str]
    version: 3.13.3
