apiVersion: v1
kind: Secret
metadata:
    name: wg-easy-secret
    namespace: wg-easy
stringData:
    password: ENC[AES256_GCM,data:aHQRcUfpTiRNJ1SgzDd/dyAyWUIodkO6,iv:uDfw0RzDfy0Xlca/j7c2scJAaSAcKs02T3w9xyiflTs=,tag:Bi6Xcm2HJ+gT0m/XBr9Fbg==,type:str]
    username: ENC[AES256_GCM,data:iyTmh3kntXLR1ba/QfU=,iv:YCPc9Qw/oM3YSH1qODLivTbm1NTyUzo4e0qbR7EvISY=,tag:yEOLBOpFs1S9EPm052E+SA==,type:str]
type: Opaque
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzK3JNLzhBZVZoaFB0SjFv
            Wktwa1FLbkg2N2xGUmoyVmJqNzBPek5FcGowCnR4aEV4NExpVDNOa05UTTZ4QklN
            WjFuOE56MW14ak1CNXc0SjAyQ3ZiUDAKLS0tIFQ2aUNRbzFITldJU3prRlRyU25F
            cUJydFBsSUd0d0MwNXgrNnV1Qyt1RDgKcigNwwhi4SUObi2h2a1tCQk6GyqqDcvD
            iRgZ92Xwf9RLypmy+kpUDYHYWl8DZ8r5qu+sacRegH5fl2oOOKvL3g==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1tew57ke6dm4dg26ds595fjj4lmf52s4j20ewnm0d2yrkmekqaqtqjv2fjq
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-23T09:52:21Z"
    mac: ENC[AES256_GCM,data:d9mGqkXhPtLIbIwYhkTm1oMVj3JTMxhpkI5pWvz8EMb2vO549mDwuHsKg16treOD5dHzQvTNNLyXfKQrfLmYFmfmqBzOM54T84JB55paSU9dLP5clBGRTHjv6gBjRl5YZYS4WsFTdGATIV9PydZjQv745/imm+5JKcP7GN0dhQ0=,iv:RhJ/qcNPKZuUYxcc8fFhGrNaJgJSGIh9lvyaIi9YKaE=,tag:7eevqAdCiIe8naQASPzjqQ==,type:str]
    version: 3.13.3
