apiVersion: v1
kind: Secret
metadata:
    name: wg-easy-secret
    namespace: wg-easy
stringData:
    password: ENC[AES256_GCM,data:RzhS2lVk0+r6ipV+hgYI6KGCjIf0ffDA,iv:fLhkdGodcH4wI5bRccrwRfcyqX9ZBJ/Wh7Kous2lxZU=,tag:0mZ/NHWnaaDcekROgz8l+g==,type:str]
    username: ENC[AES256_GCM,data:AHe2FTkeUB2p9oJQqT8=,iv:NoagttJ8MyTO68ySoWYiDMO7Sswk+ClJyW1JBwXP+B4=,tag:w4oqDUrg/ZG79kVcAd7vAw==,type:str]
type: Opaque
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzMEdDRnJWWFlOdS9Hd01u
            U0JoK2kvR21vaHVxY05ROG0vbVVzb3RETEZvCkVUb0dJUllmb25KUUp6Y2txbGZN
            NktRa0VFTVJUVzdYUnV1Y2hHOWhGNk0KLS0tIHM0MWJ4QlhNeXlyVkR1Y1RDUkRy
            ZG5yU2ovY0hGRmtpQ2NPNnNVVHFuWU0K6Jeds924+6YFrLWf/gaR/KWOnvdvSeHh
            cr1TpJmjp7uLDXwj+RY5a5O6GVSzSHvc/kWYoaeE5bSyvH5HSB9csA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1tew57ke6dm4dg26ds595fjj4lmf52s4j20ewnm0d2yrkmekqaqtqjv2fjq
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-23T11:49:59Z"
    mac: ENC[AES256_GCM,data:es4+k4IFrGT7SYc4bVPD/m31BtjH5yaN1Uzm80JxWWVUrEbB5tFvHI9gkVqlsd+3pqMGfPQeSQbVwCMS1UUK3arnYjaZ71JtE4Lnr0yWRIzIIqgCn226hN9ZmlA/+XaJdkrEhYzv7MGd2Zpi/ciemr2fF/FB+GiX2c8/Bn6+egA=,iv:4032sd3WQNeHLkTltS0gAgFMsbyzDVtRXogX3nWsVLk=,tag:9Sdo1baomYFjuV4knWo5Kw==,type:str]
    version: 3.13.3
