apiVersion: v1
kind: Secret
metadata:
    name: wg-easy-secret
    namespace: wg-easy
stringData:
    password: ENC[AES256_GCM,data:V0AWEpM+ljPh4XZPEcguZC7ZL0eU8zZs,iv:WDQuHFQ057O0edH2Uwb2BkyWeVJtSC1DkBOPZx/HiL4=,tag:x7EIEMH7qw2Aj7OQv2Vtcg==,type:str]
    username: ENC[AES256_GCM,data:RErxjA8a2DqT5iGVXk4=,iv:NtqGAYKKBGdSMR9+4dY8Hc2T3kT4LwXbz5azYOvJ2HY=,tag:GI1Maeo0OBIoZA1Cxe8XVg==,type:str]
type: Opaque
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkejRyQ3YrWEdOc2pER1VG
            eGZ0TzhMQ2ZuSWdLd1lkdzZiRGMxbFQvZ1ZJCnpzRVdOeGFsSzIrT0lTV3YvZlho
            SCtzUVFHNnBqQTY2RXBCMS9KaFgvUG8KLS0tIG5MUmE2V0sxOEN5cmFGUTROZzhJ
            Zk5BeWZPM2RCc3VmUkh4SDVobG5lc1UKgZW0N3yWNXdV7M7h3Bu8V/Zl3d6EX5U4
            H/D1auGgQyPPWq5uQYQMs7iA/7uKnw6vUcRugX/4DC/0AwldLYvN1Q==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1tew57ke6dm4dg26ds595fjj4lmf52s4j20ewnm0d2yrkmekqaqtqjv2fjq
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-23T03:51:19Z"
    mac: ENC[AES256_GCM,data:GXBvtNeOS5dxQZtOBbEJzVrVhVsC1As3vd5P7BUyUOG5v7TFEfitaV7q8DecgMsd96mm5qJgafMcORLsM/BtFO2thXesosbv//WXPUpn/igqhBAKHrkSUJEQUwkHhKsuXokWtJnHk7mPNn28GODtMvlZf9Tiw+NwPV4sQ8/H8ms=,iv:2gEKzieX3VCf3M+kP8ksCRUXdep/aXZHNh6Io2f+u38=,tag:pKLc5WRwsGP+8ToozoFNFA==,type:str]
    version: 3.13.3
