apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
stringData:
    token: ENC[AES256_GCM,data:4E3dIdROt87tU6GGU8vhhtQJmYjhYfEa,iv:5QKcS5tCdNNgpSdsxMIitiTAmtZP32/O+CBX4yLc7gQ=,tag:69WQo4uunmqB39vcJ4AMdg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJY1RjRGpYSW1FVEFqd2Yr
            SUEyZkMwQXBjMUZYcFNpRlpReU5RZklEVUFJCk0raHM3bytPN1dSc3Qwb3E5Ym11
            OTA3L2lCMjZCOTJ3d00yTUtJREFKNVkKLS0tIGxlYjBqUVRQaFZFaVBDNDQvNlhR
            U1lyNXFLMmIxRFU1OWtRWmJQaElJSHcKIHX5QsgkrAg5L692cuqQPMkUgg2VRXBg
            wnym1TUcRfBAure6rZm0zsGhqNe+6PZ0QGS6vRrO47hP6ERbMhaPbA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1tew57ke6dm4dg26ds595fjj4lmf52s4j20ewnm0d2yrkmekqaqtqjv2fjq
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-23T09:15:45Z"
    mac: ENC[AES256_GCM,data:TxxChCgty3Mp++MNEEQ5tzTMCEr17KeBFXrMGXJ033gQBPnIGA12RdWz6VHmhpP2XsD13iIKjaAbqPlfC7VNrF9rP11kGchGWEq/sBiNnaBMy87hovG35QakTJA5costP5l0IovzplSzdhCcxai77WDG5yffK73btT1gAAXw048=,iv:LDswsVnCRqx9ZwJ8iv1Y7zuLv3ZrTfxF37pDh0ds19U=,tag:jw7bFKjkcWHL3VnyL7jpuA==,type:str]
    version: 3.13.3
