apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
stringData:
    token: ENC[AES256_GCM,data:/jPsbv/rWlyKmqZyNtO8K/gB0sw2F5rf,iv:BUMC0vxaaLtP6JxXn5nqDrJO+cwJ5Toa4PLYc9Rw16U=,tag:0ZpKQLrz9qrYi839ptH3MQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUZ3lSSUVtWnQySkdUSEdw
            dS94SmJxUnI0cXZoT2ZFYkltSlc2YTF2NzEwCnBPZkIzdis2VDJCK3FtbUlyZGo1
            YTJBNXVFa2NSUldmUmRhVHg4bExxWUUKLS0tIGk3UTBBam5qVkM3NjMwSHNFb0hy
            Nm1FK1prNkgxMmtYM081VHhuZzkrZ1kKgaKDAifCl0nrCFRlF2h4n556/mXp85wg
            /UJZZ2v5ZDqFstpGRpCaiopDzqsPpmAAIxTRz8HpxJiwjN7+swpXTg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1tew57ke6dm4dg26ds595fjj4lmf52s4j20ewnm0d2yrkmekqaqtqjv2fjq
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-10T11:42:46Z"
    mac: ENC[AES256_GCM,data:uAYXbov4I4ipkxsooWq+L2b7+RQgMA5O6IDjh98LRcJtG4lpEzhPNY9dE5qBq3M9Itvz9rFXIkADHnekSXmQLOdKUoBLDxsGNBjNEJflqnAqXH7e+qnmHGLzHzUrEz5EbWaJgxLGItNlaI+UNmlP/5ZzsINadtoCNA1SVKyYWMs=,iv:1wjHUKHgfvwt8ctTYzkfZS3rrn0yo6+Kby8lzCkLM5g=,tag:syxdUY84V+kYeajPaKm2ow==,type:str]
    version: 3.13.3
