apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
stringData:
    token: ENC[AES256_GCM,data:/iLQAfexrTsvAvC3b9OteL2D+Eyp1thp,iv:izhaB/hiBXVq98cVGUo1xJoJxV4BRAuBKD6m3ztZ1q8=,tag:NM/gZNwnnfpLdb03rAYXNQ==,type:str]
sops:
    age:
        - recipient: age1tew57ke6dm4dg26ds595fjj4lmf52s4j20ewnm0d2yrkmekqaqtqjv2fjq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDeVdoQUNJUmlVZThVQXJs
            bnRibXRoTmJHYWdMV25BTXRaU3JlRE5yakdFCkpqcFkvUmpKUWxFMmk0WVBhSGNi
            RWxmZ2JKMktRRFVKWk5ZRmFHblQwSEkKLS0tIGx2dWdKY2FaNlZkQjFRd2JtMjAw
            M1ZRUjNGYmkxTkVJc0FBUTdTeUl2V1EKkO/ss80Od+1q3jZ6ffoSTo55fP1fk7EH
            c+8NLd26AAcLPAmtOM+gGkRb5NS5lOIAUskWUrsXDmkfyyBiJm64cA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-30T20:52:28Z"
    mac: ENC[AES256_GCM,data:HIIFsdU2zrIEECSNZ6jOMcYRamHAsvCG9EaMW8SBYA/NkpsbaU74RoMJ9qMOjEozL6tZuJuT7+jYYNX/J9asxDfMjNvMwc6ztwFZSRuYsVejJKiWwzBeyMNK1dm3JGStf80z0qYHi6Ro1+SrfMWmp3dYGOLNcHzuHljbn3hno5I=,iv:4xFSKPm+GT02ihhSbLKuhRqUteB2OBRjP/gQbLKP0nI=,tag:OEcwZqxXuho3wru4z1uLzQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
