---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./crds/ciliumegressgatewaypolicies.yaml
  - ./egress-gateway-policy.yaml
  - ./cilium-l2.yaml
  - ./helmvalues.yaml
  - ./helmrelease.yaml
