apiVersion: v1
kind: Secret
metadata:
    name: grafana-admin-secret
stringData:
    admin-password: ENC[AES256_GCM,data:JFJciMpzauc=,iv:h3a1PpDECMIi3fW5Sb6y4NzxZSyLNy4mtb7Ino0Y2fk=,tag:ikEWH+yJbX7efMrjTmI8mw==,type:str]
    admin-user: ENC[AES256_GCM,data:DEbrS34=,iv:q7yJCgoJ/4r9ULoun6fZoHuFPGTAaUZS4D/dKSnkGvo=,tag:BceZGqAGwRzqbXcNwBGwLQ==,type:str]
sops:
    age:
        - recipient: age1tew57ke6dm4dg26ds595fjj4lmf52s4j20ewnm0d2yrkmekqaqtqjv2fjq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBla0xla1JFVHJPNXRVL3Vi
            RHV4YzdOckJzUFRYcTY2NHRtMTlZNnlKWWhNCngyMkN1WHRtWk1qQU9LQ0dKaWY3
            ZnNZZEFXdEI2L295YnNLZW5pUDV0SUUKLS0tIFRGNUU0cDFNdEZ1RGpJUjI3WnpI
            TysxdExvTEFTeFlqcmJyU1YxV3QvdVEKwOqJmMyG6ZiJHwk2i0bjalaLLUVMB57k
            VOHzpPRFt8M5m+gYZs+DsRi/hBk//n/CR8s6foBibseFkCxzufRHeA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-30T19:05:53Z"
    mac: ENC[AES256_GCM,data:GSuZRJcOcp0IEVbpYqDMo63/q0Y5FmTST4NjSESAhnWfNQXBG7DxQPHVlu6/3+8uzX/WxZj955PnGL2QWPPSMeDq2b53WU3pmMicw4fzsAFts7nI0hHneNF97uHkopS4amoxqauw8FHvzXe1y8chAE/ONYnBEHQgSyf1cDSFCkQ=,iv:B4sQPjhKPx+zDGuU8WOzEy/Tp/hShqX0FOadaPakl+M=,tag:vo9s2mCZ8m6LORUrPEaP2A==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
