apiVersion: v1
kind: Secret
metadata:
    name: grafana-admin-secret
stringData:
    admin-password: ENC[AES256_GCM,data:kkEjjgQ1+0I=,iv:dzW/PHSMesUoyVvkNLHcTjbmpob/+klOqcm3Iicbxj0=,tag:PQe+Lhwb7w+jTgOsS5ADqA==,type:str]
    admin-user: ENC[AES256_GCM,data:XKsXlsE=,iv:kLIA5T53GP7p02AHvc1JCOvbh8JhOdqXaKaSGGmDXao=,tag:lXhBRxTragvpL+O1bMaA5Q==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvVUxkZlJJM3pPUXNhS2ho
            L0V5TzVVRkdFeThUNUlicStYY00yNUtoM2xNCnYwdDVId0Q1RzUxNjJ6M3pIMm5j
            cE1TT0tockxiL1dwNVpxaHpDRzZ1MWMKLS0tIDFQWW12aE9ycTdTWGw0OHBsalE4
            OElCUEltM1M3aGlKdjg1b0VtWjZVMFEKQdk4sm9Iofg8iVAMtmhbLA3Kk+O/Ft4B
            +HXas7JNmh3/a+FL3RFq+MTCk8aMfRSybeLijIp3J5YYCg2RHRkJsA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1tew57ke6dm4dg26ds595fjj4lmf52s4j20ewnm0d2yrkmekqaqtqjv2fjq
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-23T13:57:59Z"
    mac: ENC[AES256_GCM,data:NEZbmTZjFuV+TXVzI5wV9hdDJNiPvrFe3jgK5y6uTXLArFQuE9kcsB9JZ2NkmzeyiZCX7Wj2qO2qXxmj3WxZ2y2fuAG43H1bl/ckPYMZjFl4qn34JWcFmzPEQyAmX4cuq52DLhstM93xn7GxG/uoZ0KmMmhRm7ft9oRPKgFXb1Y=,iv:ug/p0UfYdGsIVfMh7f/7wkVWWL7xO9+pQLLs6KYcgno=,tag:EixpE9UdyUcmrXHfQml2iw==,type:str]
    version: 3.13.3
