apiVersion: v1
kind: Secret
metadata:
    name: grafana-admin-secret
stringData:
    admin-password: ENC[AES256_GCM,data:1P+80wTbLg0=,iv:AG8Gx0J+WknC0J1mn6PoJHI6w0+mbGA1UKK8zxUuGPo=,tag:TwcP0hXZMVVKjJNA2yYa2A==,type:str]
    admin-user: ENC[AES256_GCM,data:CGQGHRY=,iv:QKYse1G+wosME4MUu56iV7UvR8Ku2Na0RfsoIAZ615E=,tag:9NQF+2ycpkzvULgD9VzFig==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNbTBMK2J6OFZweW8wUE9q
            VjFrUUcwVVEza2FGb0x2Y2FDNFBBU2dheWdFClRjR1lIczhvZ0dQQlJTY25KSFd0
            cVBDNlVuN0F0cFpmZjNoZ0dlejQxU2cKLS0tIGJ6UVZNQldQS2w5cm5YcmZTU1Qv
            Z05BdlduVEVYcVJtOS9ZK2ZuVjY4Wk0KPCpVHK/N1veh6I/tDOadrEmf/TjcMraX
            LnlA58pWkED8O8vdqC3EAP507/X/aa3ivZOwoIMj86n3ZsuKT1Ni1w==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1tew57ke6dm4dg26ds595fjj4lmf52s4j20ewnm0d2yrkmekqaqtqjv2fjq
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-23T11:37:59Z"
    mac: ENC[AES256_GCM,data:iByztqnEwLOW27FensGKF/b3pOx4PIyj04wiN2oWkpjL31pClWTPYZjtQlpRKmhX0GyCTScE9CCFgyFPf/gaZYnq7yKofYQrcTn2oXMMCoL+YMtcaainhQ29J4msyvXaRTcsBfpY9PhdMym9nlJPRObySDTiu7IugryKTDh5nVo=,iv:eMzjClB0ApxYtjS2sq8x+5cznJ6zjohEVu5j+k3acSY=,tag:eO96arHufp965DwRiN8+jQ==,type:str]
    version: 3.13.3
