apiVersion: v1
kind: Secret
metadata:
    name: postgresql-secrets
    namespace: database
stringData:
    password: ENC[AES256_GCM,data:5okBXd5UHDAjw2cpfLsuhkStzkY=,iv:JtMKm/64kbh5iihfdyAAadq1o5DU1n01hWrAquEbi0A=,tag:4XxUZQGEBBq9MB74A06aQw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLTGdyWlk5dDlPYzZPSk4w
            REJlb0Zsbko3dldPc1IvemtKd2lIRkEyejNRCjVOZkIxb0wvNTBQTjQwUWFpZ29C
            UzQwRnU4TXdUdHF1YlpRYThDRlIrbW8KLS0tIHlzNkk3dG1iRlE5dm03K0NUQ0xQ
            L1crazlERDRqYXBCNTgyV2oxbUxsVlEKrk13mOdZ+lShs/4lgmCNqB4OgioivzIC
            WmKn3Wu95XdF+aNk3rhfKgfWeuAa7CK/mRez1HU1fRHiSV5Sl7RSvA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1tew57ke6dm4dg26ds595fjj4lmf52s4j20ewnm0d2yrkmekqaqtqjv2fjq
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-23T13:57:50Z"
    mac: ENC[AES256_GCM,data:9wz948L5S3QZYPEhWiAiaVBkw9aCIkgjY4ZLmcP1XQm57mfZkkfNQAztqAI4W9RDMaQ0xEEmaaNKMxBebqKHhIwgMAzMRDRV88F/vgNqEkcZZ73sSLm8eBKQ+G9r8r9Q2xz2zxJD0DKxV4ae78yclaKNy9WCG/bF4Ssq3JEd6Tk=,iv:Ss0uVJqHR3P3Cc2L/64I1e+J3zr547YVg/nBOwAWtXI=,tag:Pm05S2QZvME6x6gjgllQwA==,type:str]
    version: 3.13.3
