apiVersion: v1
kind: Secret
metadata:
    name: postgresql-secrets
    namespace: database
stringData:
    password: ENC[AES256_GCM,data:A1RPcPCIyq5KHWsW9irpxH5vKXg=,iv:XDjQqW28kSOJ/xJEx/yxTeUua0yo1Z0+92/AbgqtALU=,tag:is/QikGgGLhRzWV1ziD5oQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCb1ExdmpwZm5zelVzbkVk
            QVk2bGkrZDg2QWxPQXExZWVKWmtreHMyUENrCmhXcllrcEtFRnA1RjEzRXVSdS9X
            WHNMdlQvTEsra0JYaEg0QTJPMlRkNzgKLS0tIFBsakxEWVdhODJwTUs0bHhkN1JG
            RGNPc3I5Yi9CN0JhbUViVE4xY1pTcXcK380vMsRd44KO2VuPHYWj+9TIRrlOJkzJ
            7pp6XB/5dui9BvS1oK7FOIUAgWrLD0NehuFbjJ8E8Z5nNXGk05QfKQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1tew57ke6dm4dg26ds595fjj4lmf52s4j20ewnm0d2yrkmekqaqtqjv2fjq
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-07T14:53:58Z"
    mac: ENC[AES256_GCM,data:r9D4q9QcJbcnWGL7CX5SEdlPu/O4UHlG4TPpHf6LJm8JsP5SbDj0YSfeQA2t24AJVAxYEDkO8pfQ5PmaImT5ar342akooPbeS6lN2oYtljc0aznAq+KNlq+HsxpS8ytz9trK0RySrb7rMfSNDKAjkQSqfinUgVAAEhI5mg+w5HE=,iv:0sRykrLXvwHm+5EskR7ACGyYqiSqhl2Hww+OBeJN4NM=,tag:mHqhePLWlh8SahWrM92pvA==,type:str]
    version: 3.13.3
