apiVersion: v1
kind: Secret
metadata:
    name: postgresql-secrets
    namespace: database
stringData:
    password: ENC[AES256_GCM,data:YeFp8YuAAH0aXY/hmEFa09QrJq0=,iv:vvKr5QdVylSzWKA0Jel0zoAYcMRjW/WLbTwF7v0tn8o=,tag:uOiTP2ioqXs2axDNuDZlRQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYR0RrNDZvNFZnUG5HR3VG
            YUFWdWVDOEx3QWxWZ1JrMjl4QUs5RGtGczJnCmFTcDdjVGZhNy96bzRKNUVNbmVJ
            NGFoZExYNXVOSFltY0kzMWpTdVNJOUkKLS0tIDhVNTNIa1RlRkVSTTBHK29JbTdV
            a0RPV0NuWHUxU2Q5NFFqM050bDVQdk0K/DzYTLdx3jOH1qlppNTKSzIRbWITgt7c
            AqsKXHP8yXKUWXCQjfgDvdmwN9wPMhK5VyWqED4URoNl0nCSVvS5Ww==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1tew57ke6dm4dg26ds595fjj4lmf52s4j20ewnm0d2yrkmekqaqtqjv2fjq
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-23T09:15:43Z"
    mac: ENC[AES256_GCM,data:1t8pKLYKKRda6smR2nxJFbwbPxrlM/Wtx0XEPk/BT5zW3zv6g4a/n+Ve/neZQNaHJNawfY9LymEFJ7QlKinmYQ+6/0uxN+Hp/Tee/7K6ZB9QXNozCqcU+QP/JCVDgq4bHJodazUJZtF/80Hw+Tlh6h4FlhkPJDE/M9gGjaqpHn0=,iv:gi4YZWat3CYx85blUC3oOKg1fC0w3h/ryxRqI1w6WQc=,tag:Bk93xZ/+dd4eM4EelR8O9w==,type:str]
    version: 3.13.3
