---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: miniflux
  namespace: feeds
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 2Gi
