apiVersion: v1
kind: Secret
metadata:
    name: miniflux-secret
    namespace: feeds
stringData:
    ADMIN_PASSWORD: ENC[AES256_GCM,data:iNR6y4jHDuVEXY12s9+2SNHc0c+FswZd,iv:mX5TY67BwB1Cg+O29uJ7OtCZLat9xohQV5vKW0VUFLY=,tag:J8QzsidBb1PxR+QXlQkK/w==,type:str]
    DATABASE_URL: ENC[AES256_GCM,data:ZpacEC4lhp4eO26zzh3Z65eo1V5XwWn7o15m6kXHouSvzVHQuEezsXtx+C5AVUHolKv4rCUTnMuvKeoJggcnnK3qz1BGtTakMPyRpxQQ9FU/U+ZVpDWLxrd9lSCTPk/iJ+yt2RrPL/+GGgM=,iv:RAFkSJ5pd5jChylvkg5ivPaJVryDYY4eou5mse3oy4g=,tag:KF062xDpPlE/2BUAw99xKA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzTUJUb0dBSkJGQXRmM2ZQ
            NjhqRVNnNUlOc3l5UU9IRFh1cFBYQ0pERW1jCllNbWtyRzN2NzNUa0Z5TjhUVmFk
            WTRpQ0N0QVhjNEIyaUdPNEQyYS9KQjQKLS0tIHVBL0pQT01iNmNIc3VQQnZ1OFM2
            UENLYVIzYjRDWjB3QXV2UnMvYkN2VjQKsn7xtSw9+d2nyYzye2tFPqIugzcmbgD4
            cse4NbxkTtDXtpqKiys0eaFEor5ZtqUEiwLDRNh+2rSPGixHPOkNfQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1tew57ke6dm4dg26ds595fjj4lmf52s4j20ewnm0d2yrkmekqaqtqjv2fjq
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-05T05:25:19Z"
    mac: ENC[AES256_GCM,data:0hjLRyu1z75Jnos9aA0VPs6QlfavgkokO+z3nKdVoZUCK4qCbmOALyr7SRCIoC4C3m9P4JrxMATGyPsFVxjltEIC5hEs05rnEGJZl6C4xRYSS14zvHm9ic/CnNAn9lV93hnjzuZL3xHv25RnujBR4TFNboHYMEFJFq/hDVRwQzg=,iv:JgEpKzBTv+CTmUp0OGIRSgJIfxfQLfoZCLolOTf33RM=,tag:6e1mU7EvNFuFiryLxfn6Ig==,type:str]
    version: 3.13.3
