apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
stringData:
    api-token: ENC[AES256_GCM,data:R99bE9oIvV99hPthwJZbTkdEQv5u/yrJse8mtl3JPCeZ0mK7z6I4UA==,iv:Z48wnBJ0pbNM+bCHhF6xlc8ioskMAPZcQ2XIInxl+vI=,tag:02J0c++1US8i/oNfaq3leg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHSk0zUCtIRzZwZm4yNzhG
            RXRKUUxubWpuelZWRHJRN0p0T1JZQm5CTDJNCnNGTGdYQ1dEamZxZlJ0NWNmbmpl
            QVg2RDJrWjhMTFRMRks4aURvMmpjUUUKLS0tIGk3S3Exb1NrM09kQ0Nwd2tjME9w
            RkNxV0Z6R2NuK1J4OFBOUEl5M1dlL1kKRYq5XYsdb7lhtESZDW4qwriMs2d3uTnp
            prrzEtFd/PZMmjFwURnVbV38VEVCcut96dUBofK9O/knEUDv+V4mHg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1tew57ke6dm4dg26ds595fjj4lmf52s4j20ewnm0d2yrkmekqaqtqjv2fjq
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-11T00:18:00Z"
    mac: ENC[AES256_GCM,data:YJJaWvfG83S1kC5HoN2dzAr8U7+WScpgfAf4xwrGvFGpbmmLa1JUn8CxINQpFGfrfx4N4sZobfZNosVcyH9ld3XvCm9jIY2nJi68eYVaxrN9Lt6a9bZf+A6d2raoP5net5HqACm0QeIoRqnudlxiH2H0delVl9q/1k79zBRonsk=,iv:GMgGp+mNWsi4RZ15Rqb6tY74DXou8zVGmRbL5q216PQ=,tag:tkRQmpFDhkN5CSNg8as/jQ==,type:str]
    version: 3.13.3
