apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
stringData:
    api-token: ENC[AES256_GCM,data:2/glp+GsyRNzMMSOjceg++0lJnPxgiQlwbIgXzHabX9sXPHQwdgtew==,iv:7BfxdaSv62+w5vTKpCEvPsDYgFBaZPhblP3VsT+xAlA=,tag:4xYvDh4e4xUClko2+ugTWg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5K25zN3RZL3gyUHBjS3RH
            N3hZNU9XR1dPYTdScGVxMHhMWnBaNlR0dlU0CkRWNzdrR0tidCtIeFVKM0F5ZCtr
            Y1h0aXNXd051RXQ0QkRsZWlXa2dIdnMKLS0tIC9JOTQ1MXBVWFlkTlhEODM2SVVn
            TlVrS29YNUxMOEFJYlZTa2Q1bGYzSzgKVZRRhr85scalAUjKSSUhXd5aYCNFzdzH
            4RkUki+qCJulir/FMNqaFtfujkb/h6fXMQtembCwLetkCC4DT3+i2g==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1tew57ke6dm4dg26ds595fjj4lmf52s4j20ewnm0d2yrkmekqaqtqjv2fjq
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-07T03:35:36Z"
    mac: ENC[AES256_GCM,data:+se0VGcZnoPlPgb54eeDm0ThwKW2f+0NGTVKMJrh5kct1MhL9qjdJuWQBVThTimKNAPyh9crKu6V+/QGo22cJ6tu0mkK2Q9eHI/L8cHF7E2OsdNUZmgpD7eJ2dUFy93jcdvAdjt5gxeMzPPzrvEVUmMCQoZOm8RaZPGVv4/pYNw=,iv:IcY9GAuTz29SlnbVd+o8PRSW5DT81/WGmoua2d8h8k4=,tag:gcLjI+YWy7eY8GdkT2Wp3A==,type:str]
    version: 3.13.3
