apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
stringData:
    api-token: ENC[AES256_GCM,data:fKOmyUY/nZA4RLc3bBsQjFfUttqPFFdaKvY04J+Pn+NrSs4o74MJrQ==,iv:b+BYkkhdcJA1D74wyQu0NQRPVWwTdmYJVRqjbfRnxXQ=,tag:nTTMb4B5GNLW5DywSrhojg==,type:str]
sops:
    age:
        - recipient: age1tew57ke6dm4dg26ds595fjj4lmf52s4j20ewnm0d2yrkmekqaqtqjv2fjq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPWkZ1Q3VDSWpkWG1MVFZY
            d0NMQWducHdCKy84RUVSS3p4R3RjR3hiZWdZClREQmJOSk5BaFM5T0o3UmtzeC9p
            RmJyNUpHbWtEZWdCNnpJWXJIWjk0RkUKLS0tIHFDeStkL3lvaThlME1TbDVGRE91
            eHZLaWplL1ZVUDJUTXU0bjNXQ3BpWncKozM6o/KYysDrd0V4zsDOGYAP3+R50Ukk
            eV4ZO3xtvq6Rzbr23k+fNsfpRyrClqlvzRpqXFvZXXS8WdiYiQXbLw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-04T23:20:21Z"
    mac: ENC[AES256_GCM,data:15jZCOj9TwRp9LWViFT7fYK0yJOLS3dj3ow0Bj1K67ChVGTtBcvWh76Qau2hXI/cOil+EW3Y9p4xbeQqN22mi+suQZbBBsuFwy1ZNfBF1fAzaVKMRNljNK6Rjf8e6uyUo9YM0E5tv8m4brZXsoLk5gtD/2Sb2Smy+wCEaWcvyx8=,iv:oOgCqkAg9aMa9tYNs5Yy+uKk/m3UmnjjIITeiZvdTAA=,tag:5dfGRGPHYFIy4+kfhzOGYw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
