apiVersion: v1
kind: Secret
metadata:
    name: rss-fulltext-secret
    namespace: feeds
stringData:
    #ENC[AES256_GCM,data:egBcDe9emsaZVR8pilWbcsi3x/As+kJP+1uxP/+/gjpEvX1myfAwMC3pQ0ohDaYDMcP6abDvz2zuYFB9HO+EpxoJxrwNZmyqWXTyOeE=,iv:jnBa0lLZwKP5s1xKaXBHxdUz8+8dCbrPqQFpqGYXaps=,tag:F10jnYeNN1QYZez0idF8sA==,type:comment]
    ARTICLE_COOKIES: ENC[AES256_GCM,data:F50=,iv:odWbDII7MknJ0qMdMJZBEjK/IIHh+NpI++wprVaS+xo=,tag:/UKyH3qnHYOUJH9tFm0RSg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzN0h6VEpiOG9zdDg4NGZx
            TW41SmFLbit6Wm1nWnIvS1ZKdDJJS1djclFJClBnL2VMS3Nva0FtYk5aQXFxYXdQ
            RmxMdDhaWTVJdnJ2eWJPcUczS3F6bXMKLS0tIGF0UHRlVHVQZloxL0lOV1luVmdz
            WnVRcVdUV0o0cmp2RklSRXRjYzIxVFUKSXR/8d7fRyuc9op3BUr3YLFH7tFvWYY2
            LAuHyaeZojh6COmLJVDy2KTrmujavI8KcC/0QczB9W/WK42amPvN6w==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1tew57ke6dm4dg26ds595fjj4lmf52s4j20ewnm0d2yrkmekqaqtqjv2fjq
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-05T22:48:11Z"
    mac: ENC[AES256_GCM,data:7h9hs2QaY6fQNykeX/+9X5VCALql2tYJPObGqYw+Eq82AwJhxaeEHSkUW+BESFIZPCyK/6W24HulmO9yKw3CZQowp/kkjRY7emrZwr2MicLT41IuXCiBf/2r3MNkG4fTfFToom9dpfEngtdgBH6AE/7GKK5i4OOB/6hWwby38UU=,iv:OknUvtvbbw58FrzpN5sLCbw80nz2B9ukezgqTFJ8wEk=,tag:qIgljUkHyaRII+fb1yc5WQ==,type:str]
    version: 3.13.3
