apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    NFS_BACKUP: ENC[AES256_GCM,data:UUbnqG471NYOFw2PpENrseU=,iv:cjDA18OSIpDaRISJGJmSgmwiURIb6i4HtagOjdWE9N8=,tag:v500JXYkJY1Ac97pWIjdvw==,type:str]
    NFS_MOVIES: ENC[AES256_GCM,data:lVVFZYRlUwM77HMqAyKHRDI=,iv:KUSkR0juQgnBo3ZIzeRs1IrLjtu+51xYB972DzpWGoc=,tag:/88nr8cRX2AUPCuC8QoWLw==,type:str]
    NFS_MUSIC: ENC[AES256_GCM,data:DLWiTC35YoB/mNViC3C+OQ==,iv:k8B4jhohax1gWjWSviLj3pLGxidWlOlWxYBNqwdOBIE=,tag:7uGv3kk/pfeldleBlxZ0XA==,type:str]
    NFS_SERVER: ENC[AES256_GCM,data:NK7hDO6LSv01Y9JB,iv:nrL+d3Dv5OFq6NnxOoiKyA7N/pQpRFueUcHUn35TA9k=,tag:WN3BUalWqEN+5nAk/ddWGw==,type:str]
    NFS_TV: ENC[AES256_GCM,data:sLrXqSoZ6mYU01jrww==,iv:9cQzQtJurEMy/d2vQPaQgjgLPaucjqyhTikQx71iLxg=,tag:9TFFUeTVk4xU5wMuDdgHQQ==,type:str]
    NFS_TV2: ENC[AES256_GCM,data:Kxk/UNouSOasubXXQA==,iv:kSgbBu7LfRl9HGPDJruHlpGmYdlFq2X8ZOLKV0/B2dU=,tag:sTj7aPsxoCjZPGFJc+2mAw==,type:str]
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:b84PUWLr1wtnf+kozErUJHCVnRd3Vw==,iv:cTU7XkbCszjZuIZXbm/TCVqAqXn8JWcWguRaveFYH0s=,tag:4AEpUVcb7w0QkYc+iNm50g==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:COYTHdHmpcszXWSG5kA5zYmU9UwYfKOVcqvlr+/gykWWr+Wv,iv:45z30HquBsTfuPuyv+N0kMR9iMckQXXwSFjKpQYp2LQ=,tag:Sl0T8DzFI2S8xibeIYbl+g==,type:str]
    SECRET_DOMAIN: ENC[AES256_GCM,data:oNEGL0P61+DxcppX4nNU1Q==,iv:YyTta3Lv2IjItQn8Tzop882ijtm5PIx/dFxv7U39/II=,tag:TEMzMe5nkijfhdLpFQ8rpQ==,type:str]
sops:
    age:
        - recipient: age1tew57ke6dm4dg26ds595fjj4lmf52s4j20ewnm0d2yrkmekqaqtqjv2fjq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQTWxrZHhDbEdvZ0h1eEQr
            S1E2MUMyamxuS2tFM1A3ZzRLYVFYZGdMbkZvCnA2cEFENHErWVNVSjJ3YWZocEov
            QStvMG9mbjNLZ2ZTdlByWVpFSVlUQ2cKLS0tIDdEYmtJZG9SZnhOR3BJd25uZExU
            SXA0MFNCb3FQZ2EybjhjMGtPT2I1ZHMKy3qlkaYuSTRl7+u8htrGs9ljouH+vptY
            Rt75OFK9hnrlnR7u2MPiWu9RN2mi8R5MVvZTPExzmyJvkY6T1d5duQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-30T19:43:55Z"
    mac: ENC[AES256_GCM,data:b05/h1nWzvG/I0NJZ4rZr7Yr8Kaz5zivRXXxodjh1Dt1/5UGO/YSAc19DE9KEuYOvILySmfArecTsmKR3dnntWngTVxGLHXVCHiOCBIQwkOYjn4ppd6l38bdok7qRtP1WxaxotNy7AsTV3j4ri/mzD+8xS4gRga8BtPNN9IGn00=,iv:1Yk5HIylBORoNftULMPiBro7ktqEnCKsH34Ka2o325s=,tag:rJ2+mVcCfVMgIvvoAC9gcw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
