apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    NFS_BACKUP: ENC[AES256_GCM,data:arkyrMDWv+x3O2pUadGKkVs=,iv:tOAoOgXbGkXB77+mbesROD08O81yhczSCXSoJXkAMvM=,tag:7ldpHTCjVQwmOnHIiBx2qg==,type:str]
    NFS_MOVIES: ENC[AES256_GCM,data:wKYj87Mrjcg4B2k+9cNLszI=,iv:XdiYEIHztjZ0ysx0icuubdqOL4LuBWKeJoXecuXl6EU=,tag:/MYx/B870WRwOMhQo9b4Bw==,type:str]
    NFS_MUSIC: ENC[AES256_GCM,data:SVf92Dxvw3vo7s41dtmY1Q==,iv:UUYNgIsDg5BbWKN9fLf7kETn0JDVDJIaw7leWTerf8E=,tag:eHDqZ9LaXwYEMxJ3BwF7nQ==,type:str]
    NFS_SERVER: ENC[AES256_GCM,data:FWW80eNf0wn+dox3,iv:xDIy2J7bDJqIYxpXU31wjVlPVizbZPz0+EROlfOGN70=,tag:sQ+0SUUzNWgm6R6ZhqxVew==,type:str]
    NFS_TV: ENC[AES256_GCM,data:qx7R1CcPpZSu8NeLSQ==,iv:WKTipXkukJRW5gAWNVhFeUTHL2Wp6jY0OFv2uqqxweU=,tag:W6CZ9v5det1oW1q5m57l9Q==,type:str]
    NFS_TV2: ENC[AES256_GCM,data:6+R7g9aXz2DSy6ibnA==,iv:CZPfzQrwLnH2LSYBYJh1GNMAYByUsvuDDIcbcGVLFgU=,tag:NT0qjDWYZTrS574zCV/ULA==,type:str]
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:AXXJcTkONctZ5iyE8BR3JRXZiSxNAA==,iv:2E7IeZtJin7F7YruoGk3+I9T0hKH53SltYLRMOyJMC4=,tag:zmD94MpfuUM+fi5N3ev4Gw==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:HcD2qK2Vk+rt3obQAsp+oMQs8fxBqYgVFhwYvzlarRofRw4j,iv:6zez3BF/yFIr4hrNVEcoClO09xBH2t1/UYraIFLLIsg=,tag:7b6TnjPVDTropMqTHTA/oA==,type:str]
    SECRET_DOMAIN: ENC[AES256_GCM,data:wp5Idn6YGHybPMdK9FE4Bw==,iv:n3HJDeKbmOVWmV7efjOi8exUmWhsNyUz9GM3dsyKtSI=,tag:IIM+Gm4EET61lH9qOwLpYg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNaUh5cWJBeGhobE4rUkRh
            cWtqcEtNSVdMWkwzNENDQkx4b1JuK1VEbFg0Cmo0M1E5Tkprdy9MZXJ3MGtZS0hX
            Q2N3bzgzTDJ1NDI0RU55YVNKRTdENDAKLS0tIFJtblEzNFY3OTFXNlBOcElBSTZT
            Nm1mQjJBWm5vUXppaWtQMU9IU2F3bjgK3EZGmERyG19oSydYF5LBlfni493FMu9I
            xGyPTdI2UwvpmLtSCSYR+aR7Wr1feEcK2gJ3p20p8oQ0HjPorpnNHw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1tew57ke6dm4dg26ds595fjj4lmf52s4j20ewnm0d2yrkmekqaqtqjv2fjq
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-23T08:41:06Z"
    mac: ENC[AES256_GCM,data:aTo+fEtAdaaxEL9p6S2KAXgzatJdgbiKBv2jkreFJ4kyHnzjrgxYgKqB9dwRo0JjgEXluMTljXBPXy5ZMacHwgazc/gjTHMCCUQXpKDxjSW5bmID6dvrB+0lEkLpaJlEzUpVkiXJe5cKhVJU9e62aCYO0pO6dVpZ1ZF6TdyPuG4=,iv:iHeUV741cKofuxMu1dpIWsUnqKdSV6XBgdj3Sws6cX0=,tag:jF+qpESLfsJVkJcJznpbSA==,type:str]
    version: 3.13.3
