apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    NFS_BACKUP: ENC[AES256_GCM,data:qnBhpqlSqofMOUvRxiPeGy8=,iv:vXWtyLIzLzmunRMH6ehk8H4m2+e/EsshO4bEBrikZS4=,tag:Ts9rnKQhov4rVBvixE4MCw==,type:str]
    NFS_MOVIES: ENC[AES256_GCM,data:yZlzpcXJYfKV6fDLETqa1KE=,iv:WGMzM8AVYtzeVFVDOd9YElmD1/P9apJ7fdeYTtvBFDE=,tag:4O5xHK2XnAsNMlJnFo5Uig==,type:str]
    NFS_MUSIC: ENC[AES256_GCM,data:eG5tF30MOPYB9j9GHZJ6jA==,iv:dG/cs2ZFqwfM9QyT7PdEeXeateBmlJjcWWrROB13pM0=,tag:2WKeXpEOeV25Lb/8xzL/rg==,type:str]
    NFS_SERVER: ENC[AES256_GCM,data:lgnwquKi66UUZ7XB,iv:sBSifBsb/k6mduEL00cV686t4UqD0zS0RAKg4pjfIC0=,tag:bEq5uhCaCMnaaIiigyhhaQ==,type:str]
    NFS_TV: ENC[AES256_GCM,data:2MkGA0J7cpJIQMlccg==,iv:vwGENNE2VhDzkbZmreDs2cAs+HmlRjHlTdq7nE6PD2E=,tag:m6tB5pICUIZvI4iAA//2pg==,type:str]
    NFS_TV2: ENC[AES256_GCM,data:bzyKoQFgITSB+bZCFg==,iv:+eXj5s2O38Yq0JJNpuAsIUSKEAb+FZ95gE/MuUcEswg=,tag:xQ5C5rubfz0//F5Sdk2YDA==,type:str]
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:EGJiXTsxX/DO9Bc703/0BDUQ56N3EA==,iv:l2yib5llh4n3+981Wl5jChBBFBai4amikmwr1UgqaH8=,tag:iM8dzFlYIMJFiwXJNHj70w==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:KPU3VrZucdOBYMPh0EtMKb3LXNB9JIMsu1lVCzGvbEH7tJOY,iv:mImbSYmcnZDutpRU5P2r2VOuBHenO+X19+ATEzZc56o=,tag:/5KN9+5nQoZdmNXy1B0y1Q==,type:str]
    SECRET_DOMAIN: ENC[AES256_GCM,data:bkkBeMQ4abDgdaYRvB77eA==,iv:1i2/QDiuEFNAtzSIELZ5jstj/MhsuKcRWGe5Q8PUVGw=,tag:785F9gJ+imn7zpbpBeo40g==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBMXZFQWVSWmtvY29tVGZC
            cmxlalJZaFMwSDBLTTgrcmU3blg0RG5RMEF3CnkvWXM4TG5YRkFUS2pVSlFlUEZN
            b3cxV1drRUpxeG42UGJWTExQakl3R2cKLS0tIDN2aGMrbG9Ca05iUXZpYXdFTG9t
            SzRYb3lJUmdZbm85b3BHK0s5R1J0TXMKQnxXh1NP+KVaFiUeusAmYsLNpy6OWIY1
            G0q212jDQ7l4mJ7Ycebk2dC0GT8LqLcefTKrjXJQ43f2YZZzOKvyNA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1tew57ke6dm4dg26ds595fjj4lmf52s4j20ewnm0d2yrkmekqaqtqjv2fjq
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-23T12:36:37Z"
    mac: ENC[AES256_GCM,data:zUzgs8kozcgv/gmZQMDWfeESiUIPflwFqkKt95sWS+LmJzy1kETaWgh1AmefUd9Dkx9rOhQCSP/Gc/On4z82zTG3j1rfb1lg7hj/bd97wyFlq7twGF/J8u7N639xVXZwUUN2HKXkOMIr1UJM3tAaV83v+m0YOka1i9GfiAOAgTY=,iv:D7Fhkpbl9kLYcdvUWoxmpLOsAYDpNYGXMcN58sliWOY=,tag:fxaNEXkXBdar22wAbFCWQQ==,type:str]
    version: 3.13.3
