apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets-user
    namespace: flux-system
stringData:
    SECRET_PLACEHOLDER: ENC[AES256_GCM,data:SO3XU0u9iMuBytcp,iv:0LH7J5Jtp3/QFGvKzV2IjELe5yDVh+LaCpqjrj9DgPw=,tag:AvBpcOV4ypU/aj24otba0w==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3SFp1Z2NtMG5BWExydFF2
            WWpFM1Y0OERmZmI5VEo1b0xEN0FJMlIyVTJnCk14TmZoVlBrNElibE1aT2VaWnBp
            bXR4dDkxUUU3dVFxMXkyKzYzMVA1UXMKLS0tIG1wOTBDZzAwVjhRL3owbkdTVi8r
            cDgrQ3JiVzNYNCtVTUhrZHVFTHFmNDgKXzVNhBg86UUC7t8nR/cHYyY8N3gHcBL1
            t2jnahKnwLklmu4Ipv4Vcvf6mcphIXlPy3LSwVwjccIvd07otttiHg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1tew57ke6dm4dg26ds595fjj4lmf52s4j20ewnm0d2yrkmekqaqtqjv2fjq
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-23T08:41:06Z"
    mac: ENC[AES256_GCM,data:jvTYedYnA+01JtUxPq0qH9DOaUXWmIkerCl9zXoEAxUgEaap9K7CBTsF6ezyhow89uH2cZHrWgIbFwYZ/uPJIC6XlCsGtCkCi31c2KlPxcSEzHz+DNCJIrD6lXyDjtj0a+/NnrDsDhDRv3e0Y1kLtMUQD1QTF7XTbS5R2g3AtNQ=,iv:tb05UeBGgZkqpbhLb2F/OfNc+2ZG49Dp6gf454AxZWY=,tag:SXkJInwEKkrqzbZU2ovExA==,type:str]
    version: 3.13.3
