apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets-user
    namespace: flux-system
stringData:
    SECRET_PLACEHOLDER: ENC[AES256_GCM,data:8nxC49EP56E1I8ls,iv:HZQm8NmV6LBNM5DJT19j5y2SvaLQ3kiEL74KYJDwtEU=,tag:eGiZBUvK6j29shNbPWPrWw==,type:str]
sops:
    age:
        - recipient: age1tew57ke6dm4dg26ds595fjj4lmf52s4j20ewnm0d2yrkmekqaqtqjv2fjq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBndkV0cm5weThnV0s4QmVw
            bE40NkIwRUhYT1lvcWMzdzI0Vkh6RjhpeHhzClZnZ2hNRFZ0U294TnBtY3ovaVUx
            aWo3VmJvTm1xczhORWxDZHRENzNiQ2MKLS0tIGZoTDgwekRRZU1WN2pZcmdhemkw
            SDNjM2xjMWkyU0U4Ym1RVzNJVjByN1EKA4spYj2yvqZY8RL183FmZcSatgOYd5Xy
            GYb6udham7bYzoUtiOi6TO/2Zlq+SW2L91fy8HAgLCfG1pV/0xRIVQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-30T20:22:09Z"
    mac: ENC[AES256_GCM,data:fGWZSKySXI7N8HQeVd7ctUdGhLuYh6zg16OIUlqTJ+h5O/uM81A5VN4fpsqV/901/YWZ9igzYnxo9rcqnKECCxHBG6dLG+jEztRiwSbSuCSBBL7nNG4Se2CMEQy0Ed9wISRSPvlcCGBqw8LJjNRsxmvCQvYt4nkJgwHX2IPaEYo=,iv:UJTqMYJGNCrcVkUhlrwIGsX0Uq5F9gASy0Qker6yAio=,tag:YEfFkoD6M8k+8LWFH+LqbA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
