apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets-user
    namespace: flux-system
stringData:
    SECRET_PLACEHOLDER: ENC[AES256_GCM,data:K8CP7kOClNu0N93v,iv:Z/zwb4lgfrCOQKgUJ2tt5d4OT6tYOjMyfk2LS1x540Y=,tag:YVYYk7qDyiXsnxFsUWoTuw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUSVZTQktpV3ZVSS9KNE1t
            TGJIaWI5VjZWalhVWGFhNmVFM1dCa3BqcmxBCmpkcVQ0VjllZzlPYmwybDNWd1RL
            NVQ2QTRFdENtM3djNEluTzN2a0NSVTQKLS0tIFNSY1JpMzVxVytrK1RGd0Y3aGVk
            Umx2ZE0yYm9kaHNvSjR4ZDZhNXIyZzAKvUhQEupDMJjhUhCp+i8fKsYBlEqkRVfT
            8S9MDiD4M0v8t0OP+s7fJPosDC9SYrThMsRX2m1BiCzit1Noev1YlA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1tew57ke6dm4dg26ds595fjj4lmf52s4j20ewnm0d2yrkmekqaqtqjv2fjq
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-23T01:33:00Z"
    mac: ENC[AES256_GCM,data:yM1dJlad0Mp1sCg+QjPjBGaBVQZMCxsw8ZCa9GdC4d9l24oSE1vipMBsKpKxlt99bGK3wut0G05yCVG78iy18hIFnJq/MW1+vp9ezhbkBCzWjUfjE6eJp/hC3lotjQNTG3Wy7WYk+NrYD3uU++4gGDx33O4iUVnHB+/mEMIU31k=,iv:GrWZM5EDgFIzTxKrRJnL5mdJfxX2QY6/dwaXXqaIF9g=,tag:sdS7tQfpJ2+SZau+iyEJUw==,type:str]
    version: 3.13.3
