apiVersion: v1
kind: Secret
metadata:
    name: homepage-secret
stringData:
    HOMEPAGE_VAR_CLOUDFLARED_ACCOUNTID: ENC[AES256_GCM,data:5eZbghg5poZt79d17KLxO1hL2gOMDdCTyPnmUVnVYHI=,iv:wEH/SxS3K6FwaCqmcDDsluLj5aM2Siqfiv2oqudWPKs=,tag:x5W37xgCbe0yQlcs/vLGKw==,type:str]
    HOMEPAGE_VAR_CLOUDFLARED_API_TOKEN: ENC[AES256_GCM,data:ZiKwV4HkghKM1NvQaytGITyVq1bJ58k2w0hlYfN7SxwIW8mSCpaBHg==,iv:q4ks8NQDkfNY8521gAAwkhrq4qLSCInrpdJwHOEo8QI=,tag:82VkcPL4tcv3WZ4yNU5cSQ==,type:str]
    HOMEPAGE_VAR_CLOUDFLARED_TUNNELID: ENC[AES256_GCM,data:cxDHitKm/wzNmmGDCIwCedLb7JmcDyT0NB1HTKSi94m8unxv,iv:RPLWISrsuenNfBJcTzTScK6Dcr7O6XK304DLdQnQehw=,tag:IKzzSVlcsQab/J/HPd2HXQ==,type:str]
    HOMEPAGE_VAR_GRAFANA_PASSWORD: ENC[AES256_GCM,data:tEGCJwOtxqE=,iv:KZ7dPwvsRhKtrhty5wE/GH7zST/U5/RQtHHrrPqcybc=,tag:RX88nd6gRnp8e+XlfDXfog==,type:str]
    HOMEPAGE_VAR_GRAFANA_USERNAME: ENC[AES256_GCM,data:wuBD1tY=,iv:ZXxgtCYxGEDGXi07y3oJB+yPkTGuqCVCjEJENPhyJo0=,tag:3CmLkiTxdbkOb3HvmfCfWw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4RktWQ1JRZ2FQbG94WnlI
            eDlsR2ZBcm9jTVpjc09LLzN1alJGQ3B6RjNVCmp2eUpnM3lEY3RIWWRQYmpBeU02
            eloyVHBCb2VhUUNXc0M1d1h0R1ZDaXcKLS0tIC8zK2FvTmZZRE9iMkdnbTNRNVdL
            TXd0cUpWcVFQa3loVzhtbTZJZXduVncKzHeEMeYCj9rTnsmS9INcMOShuGm7+UuT
            aJ+lGslUdvpXZ2ELqgQgKAwrWl3AirPI+azvKnRNAUl11sF7/Qjbvg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1tew57ke6dm4dg26ds595fjj4lmf52s4j20ewnm0d2yrkmekqaqtqjv2fjq
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-10T02:53:53Z"
    mac: ENC[AES256_GCM,data:kkWzUZOy8eYlH16BW6ddbWdt3gUnCnd1f9HsChcOB9y6BBgZJPLPJAvvf2Ts1ZKXOJsLKxERhbdl6Wa14YmZC8BUW2sngqeq4vxrblSlH9A1nyTNaYCpDR47/X8xF2muW+juBHmaUOb6KZY4Sa81LpJwztQtPWsxLfPQfdHInx8=,iv:PI/iPInxSA4jldPyR2JAr76GAZjy0HdvpqvEU4hWV5o=,tag:N/pTFCdD01r13xs909Owkg==,type:str]
    version: 3.13.3
