apiVersion: v1
kind: Secret
metadata:
    name: homepage-secret
stringData:
    HOMEPAGE_VAR_CLOUDFLARED_ACCOUNTID: ENC[AES256_GCM,data:XeB0ybQbU8K1vivvz+dQGDTGPynko1JJwWrbyVFztao=,iv:IoSWrjRUVLczOcnti86xcigGiBf68UWbFolZlkcNCFc=,tag:fBjaVMGUvB+fWFjUexyjhw==,type:str]
    HOMEPAGE_VAR_CLOUDFLARED_API_TOKEN: ENC[AES256_GCM,data:j/vFtC2VqASoFTknwDMx/Qvu3u0nlyaaO4S3vkTl1vlUnOhXmgmaqw==,iv:5RDFRLs35mNU/KiiKc9OT+okejXp4BOms1sHwwi1qYU=,tag:Scf1s+1wezS0i41zWxrkxg==,type:str]
    HOMEPAGE_VAR_CLOUDFLARED_TUNNELID: ENC[AES256_GCM,data:PXKOJ1sNmKHOZQ4kmc0LfvJBP7CMWUkOGIFmNphuFI+G24Ud,iv:jq6QhkoWh+4bmSA6WGhvuSWPUrISBeq2cGRClZpwl7s=,tag:01G9HOlDdrUjcmavJQMInA==,type:str]
    HOMEPAGE_VAR_GRAFANA_PASSWORD: ENC[AES256_GCM,data:AxuWBCymlRA=,iv:p88AFz+Map4ElXXnshZyLI74CdcuMtGS0NtHwfIpq04=,tag:AmQbLKOpDYou2+LGRoPRlg==,type:str]
    HOMEPAGE_VAR_GRAFANA_USERNAME: ENC[AES256_GCM,data:x8rHe0o=,iv:FUYZmCzqoyBx31z3uLQXgoE3Bzf6yFzmI20zfXZIYJc=,tag:fy/+dvs5pbwRnKrKx/2vfw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwdi9TT2liVk5kQmtoaXhV
            a1ZVUVQ3eTF2eFF3QXFmUS9rWWZyOVNwMVcwCmhRRFFad25ocDVOUFpUTGtUcG1j
            OW9OODlxZmdvVGJQTmhnbzlwdGdrZDAKLS0tIDBUVm9WZnhqcll6aks4VFlYWnB3
            SVBUYWZ2MTRJQ0tOTjZVdUliTytReUEKoSvzP9vI7kONS1DOp6b/FXIsZHFS8DBY
            EFu4Fp+hnoZXPspJdoM7CGgDqoCJA/somC8nhcW6zXlo3yKiUtsN9g==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1tew57ke6dm4dg26ds595fjj4lmf52s4j20ewnm0d2yrkmekqaqtqjv2fjq
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-06T16:57:12Z"
    mac: ENC[AES256_GCM,data:3BvWFw1uztXjIyvpOvqDk93o2oDQzWizzIrWiPQQPIBtxkrtpiK0n1FFaNc8J/zRsv9x4porgsG+WIQHTfYHqTZIgG43lFoZJxzHOXczXyjQ2gPczEA7+fhzmEEMT8y9oKZcddhD4mKI5PWGy59Eig3bn2faSNVvEY3DEG1dxb8=,iv:XPllQH4qvOX0n2b1Crp+mGGKCiB4PavE0OMQw+I6ubI=,tag:ssDQa4aZUDmjxBNqwcf6cw==,type:str]
    version: 3.13.3
