apiVersion: v1
kind: Secret
metadata:
    name: homepage-secret
stringData:
    HOMEPAGE_VAR_CLOUDFLARED_ACCOUNTID: ENC[AES256_GCM,data:TamlA14FmFGUs7mczFXE0Gc9jS6tV/z7YfXQcW1LDDc=,iv:epgr6WQ0DhDCE17PmIIjS5522XJX5gA97XsAvGW/xzo=,tag:vKoYUURJUIHMhjElimNQbQ==,type:str]
    HOMEPAGE_VAR_CLOUDFLARED_API_TOKEN: ENC[AES256_GCM,data:VB0z6xu2P2ZzyTQpqVm7Cn/1nFefw++6Uw7q8MQta7D/tIv/HiWsCA==,iv:V5POIevTRPEeX6XS7Eqbo0zLjGG/OGYjtEffT4eQVzg=,tag:nvhDJj7zUd01+x1Oi998Cg==,type:str]
    HOMEPAGE_VAR_CLOUDFLARED_TUNNELID: ENC[AES256_GCM,data:6rMITMAUMKKxijU/XAwKOTSOUjXDhQZEhXuW1eZbcIKx2ifS,iv:QaJdyreI++/2UBduVCpO38Yi+A+TEslkXSXGkRdQCQ0=,tag:ynLp4baaqDR/XFQT7xhSiA==,type:str]
    HOMEPAGE_VAR_GRAFANA_PASSWORD: ENC[AES256_GCM,data:6dvyC+jQK9Y=,iv:WkYZoUUpAxNX30HEgiFvfs5iCqEvt5j9mRg/HHhz6gI=,tag:ICl+aL1fD6HbDWzu3Iu4rw==,type:str]
    HOMEPAGE_VAR_GRAFANA_USERNAME: ENC[AES256_GCM,data:wRLhLrU=,iv:os3CVDOIW/ZpxgTJu+4XGORenFFfQYOSZPCuKY+omFM=,tag:kcMdzuWLldZTyKQHQ8PFiw==,type:str]
sops:
    age:
        - recipient: age1tew57ke6dm4dg26ds595fjj4lmf52s4j20ewnm0d2yrkmekqaqtqjv2fjq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzSm5WNlVINGs2UzdONW1o
            SE9WM3lBeHR5S1dYVGE4SU5NR2FxbXNSNW1ZCkJETDZWOTFWZzJJb2hjVHFjbThB
            SzVtdWhjUmpTQzdFNFhPWStJL3FNejQKLS0tICswT3FuSFFHMGxsL3lKdk1lZEZh
            Y1R2cTkwRFk1eDIwREZ0Rm52aEJjaEEKa2ts4YewGC1VEJTSuU4paz3at3Dchrqa
            /54ImdjF3jV1vJvP5YqUyaaQ3nj33iF5Og8swW5L4zr+yhi3232jRA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-30T20:52:33Z"
    mac: ENC[AES256_GCM,data:BOlOIXGNVnlzjO72UAjHpwK4FOwDGo5SQW159ntPXT/nHDCZPC1LvL08xdNy3li/8zFXm+ArkzS9kU8suVeU9VcbmVfcMoFh5nqIQia0RWby2Wdhbw1pzqhmNy7DnPio9TiOk5hBs5nQOnue4FcG0rkp0bxtse0khsF8KF01DdY=,iv:RPYX3aKVsapDu7bxQcQLRQ7LssZDX+JE4oZYVfE4Ieg=,tag:dBQdV4i/jg9udenDlCweUQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
