apiVersion: v1
kind: Secret
metadata:
    name: lidarr-secret
stringData:
    arlToken: ENC[AES256_GCM,data:lDRS1wTLUvPswdC3ON1OrU+gqdSV5C925tyNtyta+5TJIiCPQ9THZzAXsjNfpzASNQa5N5bSWJpIl7H54irNDOE7xSHilbyimylmuyVO2AFiStdjIsncxJEG8QV0oKGSGsQE3fvnlSfnCc001Mt4pHnHM0d3iJO3vlheU8k4ZFXb2XODO/NXNfDKy0GKKSHvNs8Ff3iq7DYGdvgOEMd42AzK6pDrFZd4VrPh257ATlIWiyITmEwiWn4OY/cm76b4,iv:7yeqxv+zFu8FCC9SINu1zrB4WeCA5y7M235uYC5dLTE=,tag:097aBSCH5bkecSoii/yScw==,type:str]
    plexToken: ENC[AES256_GCM,data:cZptKus03+/JQdqZEZ5v71i+wSw=,iv:gaaz22Equa+ujJA30c39zEa6yHqeMdVoLuL1cCZ7ypI=,tag:Uk6crg1P+qagpUVFR3cJ6w==,type:str]
    plexUrl: ENC[AES256_GCM,data:PDz247rpVpaITdL2,iv:rfMgIXdO/ZrMtlSm55jCHAhfXyCXRsArHJ48UZMb18E=,tag:7RNwQkCIkB7Etra37LT/3g==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArVVJHL1laRTFjRkNWZ3Vp
            WXl2Z3kyRjlxK0hYdzl2L1JaT1RVMWxNTjNVCllLMmdMeG4rWDRXZGlyVEtzNXp1
            QVBTQ2hpbWdCZVJrS1lpQ0NjdWN3cWsKLS0tIEYyZ2NnMDdLUEsxVjFaRHhQRVlv
            TytTcVFQdUo0TjhKU0xmOVM1dTRYd0kKVZ+sJkxiC0S2WBbQSikVG1q35GIWn11z
            mrMjtrks/qaW1pRY0d9QhiAcr4VwnXSAQDLox2riIXoMSolhoeOM/w==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1tew57ke6dm4dg26ds595fjj4lmf52s4j20ewnm0d2yrkmekqaqtqjv2fjq
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-23T12:36:35Z"
    mac: ENC[AES256_GCM,data:ZSiM3mIRZh3OA1dsj2g02x8qmSv2RHTUFjqwyJ27uaRufPLvhbbAM4haT2CnIHZSTHbD+u0Xy1WsJ1a6DGQwioH/xZfk1fVm19C54flp23PLV0uVh/KoF0ShqqNJxiRVK3ppXMBO6Pa/9UzUNUdEFRrTNlhCYncpIdL8WT+Bw00=,iv:MLL94DemVppVR0GVxItNoFUJCsb0KpMp9NK2vYXl4Yk=,tag:WioZvawZyZfqnrhBMa9CoA==,type:str]
    version: 3.13.3
