apiVersion: v1
kind: Secret
metadata:
    name: lidarr-secret
stringData:
    arlToken: ENC[AES256_GCM,data:1c2UMCkImq6GsSA8rw/5iZOKklQzutHhgbKK+WnthoJIdmH0Zs4hsIRpW7Xf3EF2qvfGhcozJG5lZ/cLo8P2FVvUyrbssQebX1XKr1TWJTszCTTuZia+77SE2mr1pmIg9idcHflZXe4tB5EOcBk99mdpw/lrMnvxD+/ju4AJFcilyT+qJ+WjGcNogwKkmGdu/t+C5rWRluJVUUnsI37Sv7lOxB6ACCPEZpyyKIJoTK4qtJLxzB2Q7enpcvl4Z72O,iv:Y5nl5Hkpnd6XKsbqoq/HtxqBJCdjhoG9jJJ6Y+qHscw=,tag:7HLTvNX0aqgm5/i4QRMYOA==,type:str]
    plexToken: ENC[AES256_GCM,data:I/zscrwKgZXpNJyrePUVa1DLSUg=,iv:g0isLO7GlB3DEPeQB/20cxmS1yyRAiniBO4uLC99ZfI=,tag:DPuYoOlqCscnyph3TvKCxw==,type:str]
    plexUrl: ENC[AES256_GCM,data:SCzff1hG039d0QCH,iv:8aenAsC23XrGolTqAY+/s6x8HLN9C0exVa7cnrMhfhw=,tag:oA0fdySID+PAqLLg5yFRag==,type:str]
sops:
    age:
        - recipient: age1tew57ke6dm4dg26ds595fjj4lmf52s4j20ewnm0d2yrkmekqaqtqjv2fjq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVTHNFYU1pMXlHYWlhWTRs
            QTYySXFEcS8zODNHNGs3RzVlRTI4b3liUUhjCnk1VlBXK3puck9LS3pJQlpDOGpJ
            OU9peW5rTDdsQlhJRHl2UTEyMnh4YWMKLS0tIDl0ZEYySmJwQ1pjV3lHNEtmQ1g4
            WTVwQ0NmZ0pZQmQ1cnd2V0kyb3VyUDgKn6cEfUpCi+SWUOKz6Es1itT/l7MGcoQ2
            8RXCPL6ipL0C/cOQZGjb2PsUJRadjOq6xXgAUEjzj2cTyTL3lP5Lfg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-30T19:05:49Z"
    mac: ENC[AES256_GCM,data:S9Tjz0dLycYH+qNmvdK4WKeyyHMBXv/90ndmHKaackshwgwS9CGaoGA2LCpWhkIRGPnhe8LePnYGSeRK7yuTOb6fSCiXLDv7QUAOwBVC26l8QdGViY6kdTRY0sdKQyBEyQYLW/ITlSoLCyc3p/sM0h6nzZsgbe0vsUr7BIui9yA=,iv:iEuWZjYWLdfTgkxyMKWKwDM+MP0IVsV8vp3ReWmi+1k=,tag:As69cdwfwyhKEXDpKjz9tw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
