apiVersion: v1
kind: Secret
metadata:
    name: lidarr-secret
stringData:
    arlToken: ENC[AES256_GCM,data:XnJM5ySO6yAYLoLWUPnww//kt/xlzvaP5jdeoQWuRvn28lH/Qh5TqbeEc2N8tHH9QwpnzzGWfkl0qyH552hHoXmclXpiO/pFQZf1Bm+ybcl2wHWtowpEoT1lvTBQJNw4taGlN4emgrUOcdJ4Zg42XGsBujewPa3djhERSlac+T8VGC+9Lbaq21qFG98SQz7PFAkeogx481kRkC11Q/+gL5QzT+3mEgTCZgJACf7FzmfUQgd1RULY5lfU3kAWmcug,iv:3Y8ikXc9upVfTEtlqGANYodJxS+knmvsICF05UfUi5E=,tag:V9H2bjQNR9tQkA8hrRzfFw==,type:str]
    plexToken: ENC[AES256_GCM,data:0sG4nmmkm0AIi+z5s6azQ3rNIWQ=,iv:vF0uEZ8P8XPdCGoRpUiwYXo9aX8+kHI4pCg7or3mbNU=,tag:7WQq6iSxIpAWT38LZwqYwQ==,type:str]
    plexUrl: ENC[AES256_GCM,data:r9P5hUQfgES+kW91,iv:N00qAKTlUYNG6N5xnqx/+eXELIdXNbnnwL6Vz804NcM=,tag:y/7h5rIqLsj9NES1zVLscA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvQTM0Q1luKy96NXUwNExo
            VS9Tc2JJWnZKbDd3QWV6SjRXSStuanhSV2dzCjZrc3NYYW11aDNUZU96RHk4NjBh
            bWdnbTZqckJHbWgvZms5MUxoYkkvdUUKLS0tIDA1VGdtdEdGYldZbkJaTVExVC9W
            TTJuUHhwTXJiVXY3UDRzR3hDRytGRGsKnPTy6+zRV8LUprJki2PxgM1voHPSxCK3
            vYkJBpNvQ2oOPFXbPQEUGeDZWSEOBRM5w/iQyrfANU+YtCAxHV+HRg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1tew57ke6dm4dg26ds595fjj4lmf52s4j20ewnm0d2yrkmekqaqtqjv2fjq
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-23T12:09:02Z"
    mac: ENC[AES256_GCM,data:iKzUiU/ejNo/WA2xbGNoxx+Ok4kbv9oykjfPn9VUP+y29INsIJ0nzz6S1caNsB5q7QSLZo+JlAXroqGCF9aRzBiuTtBsuAkfz1Na+TA+wYwaNAbI9YkEpv6LcQoGCZfnFY+53gYN8YWt9gtGhT08lb0fY7JElchNXiFnUMiPqTg=,iv:mxBZAY0uV15XLhVjMoHweUQh2pT+A5/lx68sMMlPQvk=,tag:tXE5PJ0Ru7TeVc2dryvAqQ==,type:str]
    version: 3.13.3
