apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
stringData:
    api-token: ENC[AES256_GCM,data:gP5JVbW4Us+muKPJ3UQoM4TMB75MZqmSD6txhLGitS2e1xUw2E1JuQ==,iv:NZV95tKdHnreZh/qG85C1pzDdOxkQSRSkRLrYD9LVno=,tag:hKfIR4+P2cj3JXwQZcb3og==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGV2Z2dWt3OE8xQUxFeU5H
            ZVZ1VjBzcm0rblFLcS9jTFpkczJSaHYwMkNFCjVWQzVxNGVmaVBXN0dBdVcwYnNl
            bDVEZzhGSkJlTHdJT3dKRCtOM1ExYzgKLS0tIG04ZkFCM0UzTDFXd2pvdHExdHJw
            Nk5HdUlMeE5EVHBlVXhhby90WCtnRmsKzT7reQ1pXCplVTxJwEUzXSXdnjImRJ3a
            H+vKT1NCCalnf1VzHN5aGKZJBIXwk6VEK+9Y8EhxX2HDNTLkyyXZ7w==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1tew57ke6dm4dg26ds595fjj4lmf52s4j20ewnm0d2yrkmekqaqtqjv2fjq
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-23T04:37:00Z"
    mac: ENC[AES256_GCM,data:qB9FJeHQi/MKjhGV6mjs+2qZ2Uowrvwisl430PTYvPJuDdnZxWzl4LFYWgB9RVoRw54hOsEmhjcsBxebcywAmeyQyoGSMjkOFqdtk/qFW8u03GzBjlTr2fPAP0iLJDH7NR6ZmEBlGlTkau7j+3HKQM2UBFZfE+WdJBDbU+oeA1k=,iv:DIFMP/WIz1wNGLCrIgUtIBOHcM8Om1O518IF7XHmN2s=,tag:1fEMJGkcDZfghL2VVWkKWA==,type:str]
    version: 3.13.3
