apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
stringData:
    api-token: ENC[AES256_GCM,data:0jcpLjZNzHGBsFE8sIIgWX11tafyNeLY24XJXxT4JTiryFa3K3o6jA==,iv:OQfQTLcoTnaoElxAJez/kFy0FUu/C0iNtXvk2UD0By8=,tag:vu5bWLDA7x6ULGIGCqI5kA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKNVRBc3MvR0NyUS9vUXNI
            M3E4aElJTkJhSHdOYVZ0YlY1QTY4d2VVakdzCkJTeG9CUVp3N2tCRHc0ajVIS3Nz
            UlBRLzErRWlKZHB5TDVZRlpFRXRRTHMKLS0tICtBT01LYVhlNDdtbVJZR3o5QU1E
            VTV4MWRHTmFPcDFvSnNaRXl0eXRISW8KJ9aKIrWEDTb4S5JMeMaNTblx81HwxsOv
            6wWaRYWnvJ+rvBF+c+62Cr8cgBmiOB6T9EpT3jrzYmzdb8EnPOxhFw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1tew57ke6dm4dg26ds595fjj4lmf52s4j20ewnm0d2yrkmekqaqtqjv2fjq
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-07T01:03:18Z"
    mac: ENC[AES256_GCM,data:BSJripu8EPXs8Vaj9H6SvXw9PMEKN81xeH4mfcvQpVt5IZYbjk9veKDsBKB/LqH7N7MnClrI0xrUUsQxtRU7wdJJtZGVbhLmaztULqSDeT1BWf+FWsxETdgMf8jrmzkVbTdthua0PjBekoSqwEzPep9MLs3ASYyLOJ6fBSSd3bs=,iv:ZGFWK4AS6yZkU7Fl8kP+2b/ov2cVdnpXSJ4KB69YYUI=,tag:NJx5XuZv0n4Z4fl6q+31aw==,type:str]
    version: 3.13.3
