apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
stringData:
    api-token: ENC[AES256_GCM,data:hTDwNV2677yeHMCTSp04NP6IqXTP3gB8aMe+x4UBUY5ApUWFo7urzQ==,iv:ELj2bnqlSbBr9llLKnoPizRMoHtzkncasFExmhyNEhk=,tag:wBgm0HU2dvbYE7PpSCpkEQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUeFdGaXR4N2dPenI3cWhn
            NW1DVnpKRzlJMUd2allySDBuVTl5ZzFiQ2hjCnJUdStHZll5aUg1NXRoT0k4ODF3
            VWxvMmRJeW1jSkpWQUZWc1hXb0N5TXMKLS0tIFpZN2hHMGJnRG16cjBXWjNSMHhz
            WHdkUWwrRW1QVDA4RVlmRUMwR2ZTalkKnbePJhheQF1uycWBYyH21Qjlmw8xEhhM
            bbSwiqgcklYse1PaZFwQSPlEqRQFx+nXa0YqsUK3eGmqoCaoPEscrw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1tew57ke6dm4dg26ds595fjj4lmf52s4j20ewnm0d2yrkmekqaqtqjv2fjq
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-14T16:22:27Z"
    mac: ENC[AES256_GCM,data:Dg4f6S4ldOW3M4FDPbogxSIuP8reuAc+6ZU5xysjdx1hRVA8y4ygZnP1B/lOfsXpimJM7oan+/ZCMwt8TBccoxWwcBbo+DkJFPNuIwMtrc4Gh+DfuM2z8UkvJpP6L6HiJAnl6fJ0UWG9b7VrG0ElzL5V6KwCLeBqKSRYW56OLJg=,iv:UTXR2MUTo5W2OrH1h8DCY6P2q005cZrwTUbKF2UOPi0=,tag:AyiVCUDpt3rB6p4xUx/l+g==,type:str]
    version: 3.13.3
